#aqui vai ser a parte responsavel pelos itens do jogo
class Item:
    def __init__(self, nome, tipo, valor, peso=1, raridade="Comum"):
        self.nome = nome
        self.tipo = tipo # "Consumivel", "Arma", "Armadura"
        self.valor = valor
        self.peso = peso
        self.raridade = raridade

    def __repr__(self):
        return f"{self.nome} ({self.raridade})"

class Consumivel(Item):
    def __init__(self, nome, valor, cura_hp=0, reduz_fadiga=0, peso=0.5):
        super().__init__(nome, "Consumivel", valor, peso)
        self.cura_hp = cura_hp
        self.reduz_fadiga = reduz_fadiga

class Equipamento(Item):
    def __init__(self, nome, tipo, valor, bonus_ataque=0, bonus_defesa=0, peso=2):
        super().__init__(nome, tipo, valor, peso)
        self.bonus_ataque = bonus_ataque
        self.bonus_defesa = bonus_defesa

# --- BANCO DE DADOS DE ITENS INICIAIS ---
ITENS_BASICOS = {
    "pocao_pequena": Consumivel("Poção de Vida P", 10, cura_hp=20),
    "maca": Consumivel("Maçã", 2, cura_hp=5, reduz_fadiga=10),
    "espada_ferro": Equipamento("Espada de Ferro", "Arma", 50, bonus_ataque=5),
    "escudo_madeira": Equipamento("Escudo de Madeira", "Armadura", 30, bonus_defesa=3)
}

# --- ITENS GUERREIRO: COMUM (01-50) ---
ITENS_GUERREIRO_COMUM = {
    # ARMAS (Dano base: 2 a 8)
    "espada_treino": Equipamento("Espada de Treino", "Arma", 10, bonus_ataque=2, peso=1.5, raridade="Comum"),
    "machado_ferrugem": Equipamento("Machado Enferrujado", "Arma", 15, bonus_ataque=4, peso=4.0, raridade="Comum"),
    "clava_madeira": Equipamento("Clava de Madeira", "Arma", 8, bonus_ataque=3, peso=3.0, raridade="Comum"),
    "lança_ponta_pedra": Equipamento("Lança de Ponta de Pedra", "Arma", 12, bonus_ataque=4, peso=2.5, raridade="Comum"),
    "adaga_cega": Equipamento("Adaga Cega", "Arma", 5, bonus_ataque=1, peso=0.5, raridade="Comum"),
    "maca_estevao": Equipamento("Maça de Carvalho", "Arma", 20, bonus_ataque=5, peso=3.5, raridade="Comum"),
    "espada_curta_velha": Equipamento("Espada Curta Velha", "Arma", 25, bonus_ataque=5, peso=2.0, raridade="Comum"),
    "machado_batalha_gasto": Equipamento("Machado de Batalha Gasto", "Arma", 30, bonus_ataque=6, peso=4.5, raridade="Comum"),
    "alabarda_quebrada": Equipamento("Alabarda Quebrada", "Arma", 35, bonus_ataque=7, peso=5.0, raridade="Comum"),
    "espada_bastarda_simples": Equipamento("Espada Bastarda Simples", "Arma", 40, bonus_ataque=8, peso=4.0, raridade="Comum"),

    # ARMADURAS (Defesa base: 1 a 6)
    "gibao_couro_velho": Equipamento("Gibão de Couro Velho", "Armadura", 15, bonus_defesa=2, peso=3.0, raridade="Comum"),
    "peitoral_ferro_trincado": Equipamento("Peitoral de Ferro Trincado", "Armadura", 50, bonus_defesa=5, peso=8.0, raridade="Comum"),
    "elmo_aberto": Equipamento("Elmo de Ferro Aberto", "Armadura", 20, bonus_defesa=2, peso=2.0, raridade="Comum"),
    "grevas_couro": Equipamento("Grevas de Couro Gasto", "Armadura", 12, bonus_defesa=1, peso=1.5, raridade="Comum"),
    "manoplas_ferrugem": Equipamento("Manoplas Enferrujadas", "Armadura", 10, bonus_defesa=1, peso=1.0, raridade="Comum"),
    "escudo_carcomido": Equipamento("Escudo de Madeira Carcomida", "Armadura", 15, bonus_defesa=3, peso=4.0, raridade="Comum"),
    "broquel_ferro": Equipamento("Broquel de Ferro Simples", "Armadura", 25, bonus_defesa=4, peso=3.0, raridade="Comum"),
    "ombreiras_sucata": Equipamento("Ombreiras de Sucata", "Armadura", 8, bonus_defesa=1, peso=2.5, raridade="Comum"),
    "cota_malha_incompleta": Equipamento("Cota de Malha Incompleta", "Armadura", 45, bonus_defesa=4, peso=6.0, raridade="Comum"),
    "perneiras_ferro": Equipamento("Perneiras de Ferro Básicas", "Armadura", 30, bonus_defesa=3, peso=4.0, raridade="Comum"),

    # ARMAS (Dano base: 6 a 10) - Onde o Rank E começa a brilhar
    "espada_recruta_rank_e": Equipamento("Espada de Recruta (Rank E)", "Arma", 45, bonus_ataque=9, peso=2.5, raridade="Comum"),
    "machado_lenhador_pesado": Equipamento("Machado de Lenhador Pesado", "Arma", 42, bonus_ataque=8, peso=5.5, raridade="Comum"),
    "espada_ferro_rompida": Equipamento("Espada de Ferro Rompida", "Arma", 18, bonus_ataque=5, peso=1.8, raridade="Comum"),
    "lança_guarda_cidade": Equipamento("Lança de Guarda da Cidade", "Arma", 55, bonus_ataque=10, peso=3.5, raridade="Comum"),
    "clava_pregos": Equipamento("Clava de Pregos Enferrujados", "Arma", 30, bonus_ataque=7, peso=4.0, raridade="Comum"),
    "facão_selvagem": Equipamento("Facão Selvagem Gasto", "Arma", 28, bonus_ataque=6, peso=1.2, raridade="Comum"),
    "martelo_ferreiro_velho": Equipamento("Martelo de Ferreiro Velho", "Arma", 32, bonus_ataque=7, peso=5.0, raridade="Comum"),
    "espada_curta_soldado": Equipamento("Espada Curta de Soldado Raso", "Arma", 60, bonus_ataque=10, peso=2.2, raridade="Comum"),
    "gládio_arena_suja": Equipamento("Gládio de Arena Suja", "Arma", 48, bonus_ataque=9, peso=2.4, raridade="Comum"),
    "mangual_simples": Equipamento("Mangual de Ferro Simples", "Arma", 52, bonus_ataque=9, peso=4.5, raridade="Comum"),
    "espada_longa_lascada": Equipamento("Espada Longa Lascada", "Arma", 40, bonus_ataque=8, peso=3.0, raridade="Comum"),
    "picareta_mineiro_combate": Equipamento("Picareta de Mineiro (Ajustada)", "Arma", 35, bonus_ataque=7, peso=4.8, raridade="Comum"),
    "porrete_carcereiro": Equipamento("Porrete de Carcereiro", "Arma", 25, bonus_ataque=6, peso=3.2, raridade="Comum"),
    "lamina_caçador_rank_e": Equipamento("Lâmina de Caçador (Rank E)", "Arma", 65, bonus_ataque=11, peso=2.0, raridade="Comum"),
    "tridente_pescador_ferro": Equipamento("Tridente de Pesca de Ferro", "Arma", 38, bonus_ataque=7, peso=3.8, raridade="Comum"),

    # ARMADURAS (Defesa base: 3 a 7)
    "peitoral_couro_batido": Equipamento("Peitoral de Couro Batido", "Armadura", 70, bonus_defesa=6, peso=4.0, raridade="Comum"),
    "elmo_infantaria_rank_e": Equipamento("Elmo de Infantaria (Rank E)", "Armadura", 40, bonus_defesa=4, peso=2.5, raridade="Comum"),
    "escudo_madeira_reforçado": Equipamento("Escudo de Madeira Reforçado", "Armadura", 55, bonus_defesa=5, peso=5.0, raridade="Comum"),
    "manoplas_couro_pregos": Equipamento("Manoplas de Couro com Pregos", "Armadura", 25, bonus_defesa=2, peso=1.2, raridade="Comum"),
    "perneiras_malha_velha": Equipamento("Perneiras de Malha Velha", "Armadura", 50, bonus_defesa=5, peso=4.5, raridade="Comum"),
    "ombreiras_ferro_simples": Equipamento("Ombreiras de Ferro Simples", "Armadura", 30, bonus_defesa=3, peso=2.8, raridade="Comum"),
    "botas_marcha_pesada": Equipamento("Botas de Marcha Pesada", "Armadura", 28, bonus_defesa=2, peso=2.0, raridade="Comum"),
    "capuz_couro_grosseiro": Equipamento("Capuz de Couro Grosseiro", "Armadura", 20, bonus_defesa=2, peso=0.8, raridade="Comum"),
    "broquel_madeira_ferro": Equipamento("Broquel de Madeira e Ferro", "Armadura", 45, bonus_defesa=4, peso=3.2, raridade="Comum"),
    "proteção_braço_rank_e": Equipamento("Proteção de Braço (Rank E)", "Armadura", 32, bonus_defesa=3, peso=1.5, raridade="Comum"),
    "escudo_redondo_gasto": Equipamento("Escudo Redondo Gasto", "Armadura", 35, bonus_defesa=4, peso=4.2, raridade="Comum"),
    "cinto_couro_placas": Equipamento("Cinto de Couro com Placas", "Armadura", 15, bonus_defesa=1, peso=1.0, raridade="Comum"),
    "gorjal_ferro_bruto": Equipamento("Gorjal de Ferro Bruto", "Armadura", 22, bonus_defesa=2, peso=2.0, raridade="Comum"),
    "tunica_linho_reforçada": Equipamento("Túnica de Linho Reforçada", "Armadura", 12, bonus_defesa=1, peso=0.5, raridade="Comum"),
    "escudo_oval_soldado": Equipamento("Escudo Oval de Soldado", "Armadura", 60, bonus_defesa=6, peso=5.5, raridade="Comum"),
}

# --- ITENS GUERREIRO: INCOMUM (Rank D) (01-50) ---
ITENS_GUERREIRO_INCOMUM = {
    # ARMAS (Dano base: 12 a 18)
    "espada_aço_guarda": Equipamento("Espada de Aço da Guarda", "Arma", 150, bonus_ataque=14, peso=2.5, raridade="Incomum"),
    "machado_batalha_duplo": Equipamento("Machado de Batalha Duplo", "Arma", 180, bonus_ataque=16, peso=5.0, raridade="Incomum"),
    "espada_larga_mercenario": Equipamento("Espada Larga de Mercenário", "Arma", 200, bonus_ataque=18, peso=4.5, raridade="Incomum"),
    "lança_reforçada_aço": Equipamento("Lança Reforçada de Aço", "Arma", 140, bonus_ataque=13, peso=3.2, raridade="Incomum"),
    "maça_flangeada": Equipamento("Maça Flangeada de Ferro", "Arma", 160, bonus_ataque=15, peso=4.0, raridade="Incomum"),
    "espada_gladio_imperial": Equipamento("Gládio Imperial", "Arma", 170, bonus_ataque=15, peso=2.2, raridade="Incomum"),
    "espada_curta_afiada": Equipamento("Espada Curta Afiada (Rank D)", "Arma", 130, bonus_ataque=12, peso=1.8, raridade="Incomum"),
    "martelo_guerra_pedra": Equipamento("Martelo de Guerra de Pedra", "Arma", 155, bonus_ataque=15, peso=6.5, raridade="Incomum"),
    "alabarda_sentinela": Equipamento("Alabarda de Sentinela", "Arma", 190, bonus_ataque=17, peso=5.5, raridade="Incomum"),
    "clava_espinhos_aço": Equipamento("Clava de Espinhos de Aço", "Arma", 145, bonus_ataque=14, peso=4.2, raridade="Incomum"),
    "sabre_infantaria": Equipamento("Sabre de Infantaria", "Arma", 165, bonus_ataque=15, peso=2.0, raridade="Incomum"),
    "foice_combate_mercenario": Equipamento("Foice de Combate", "Arma", 150, bonus_ataque=14, peso=3.8, raridade="Incomum"),
    "espada_bastarda_aço": Equipamento("Espada Bastarda de Aço", "Arma", 210, bonus_ataque=18, peso=4.2, raridade="Incomum"),
    "machado_arremesso_aço": Equipamento("Machado de Arremesso Balanceado", "Arma", 120, bonus_ataque=12, peso=2.0, raridade="Incomum"),
    "mangual_aço_pesado": Equipamento("Mangual de Aço Pesado", "Arma", 185, bonus_ataque=17, peso=4.8, raridade="Incomum"),
    "espada_viking_reforçada": Equipamento("Espada Viking Reforçada", "Arma", 175, bonus_ataque=16, peso=2.8, raridade="Incomum"),
    "lança_caçador_rank_d": Equipamento("Lança de Caçador (Rank D)", "Arma", 160, bonus_ataque=14, peso=3.0, raridade="Incomum"),
    "cutelo_carniceiro_gigante": Equipamento("Cutelo de Carniceiro Gigante", "Arma", 140, bonus_ataque=13, peso=5.2, raridade="Incomum"),
    "picareta_guerra_militar": Equipamento("Picareta de Guerra Militar", "Arma", 155, bonus_ataque=15, peso=4.5, raridade="Incomum"),
    "espada_cavalaria_leve": Equipamento("Espada de Cavalaria Leve", "Arma", 180, bonus_ataque=16, peso=2.5, raridade="Incomum"),
    "adaga_grande_aço": Equipamento("Adaga Grande de Aço", "Arma", 110, bonus_ataque=11, peso=0.8, raridade="Incomum"),
    "espada_longa_viajante": Equipamento("Espada Longa do Viajante", "Arma", 195, bonus_ataque=17, peso=3.0, raridade="Incomum"),
    "clava_osso_monstro": Equipamento("Clava de Osso de Monstro", "Arma", 150, bonus_ataque=14, peso=4.0, raridade="Incomum"),
    "machado_barbudo": Equipamento("Machado Barbudo", "Arma", 170, bonus_ataque=16, peso=4.4, raridade="Incomum"),
    "espada_rank_d_padrao": Equipamento("Espada Padrão (Rank D)", "Arma", 180, bonus_ataque=16, peso=3.0, raridade="Incomum"),

    # ARMADURAS (Defesa base: 8 a 15)
    "peitoral_aço_recrutamento": Equipamento("Peitoral de Aço de Recrutamento", "Armadura", 250, bonus_defesa=12, peso=10.0, raridade="Incomum"),
    "elmo_aço_fechado": Equipamento("Elmo de Aço Fechado", "Armadura", 120, bonus_defesa=6, peso=3.5, raridade="Incomum"),
    "escudo_aço_redondo": Equipamento("Escudo de Aço Redondo", "Armadura", 150, bonus_defesa=9, peso=6.0, raridade="Incomum"),
    "manoplas_placas_aço": Equipamento("Manoplas de Placas de Aço", "Armadura", 100, bonus_defesa=4, peso=2.0, raridade="Incomum"),
    "grevas_aço_polido": Equipamento("Grevas de Aço Polido", "Armadura", 110, bonus_defesa=5, peso=3.8, raridade="Incomum"),
    "armadura_couro_tachonado": Equipamento("Armadura de Couro Tachonado", "Armadura", 180, bonus_defesa=8, peso=5.0, raridade="Incomum"),
    "escudo_aquecer_aço": Equipamento("Escudo Aquecedor de Aço", "Armadura", 220, bonus_defesa=11, peso=7.0, raridade="Incomum"),
    "ombreiras_ferro_reforçado": Equipamento("Ombreiras de Ferro Reforçado", "Armadura", 90, bonus_defesa=4, peso=3.5, raridade="Incomum"),
    "botas_placas_mercenario": Equipamento("Botas de Placas de Mercenário", "Armadura", 95, bonus_defesa=4, peso=2.5, raridade="Incomum"),
    "elmo_guerreiro_rank_d": Equipamento("Elmo de Guerreiro (Rank D)", "Armadura", 130, bonus_defesa=7, peso=3.2, raridade="Incomum"),
    "cota_malha_reforçada": Equipamento("Cota de Malha Reforçada", "Armadura", 300, bonus_defesa=14, peso=12.0, raridade="Incomum"),
    "gorjal_aço_pesado": Equipamento("Gorjal de Aço Pesado", "Armadura", 80, bonus_defesa=3, peso=2.5, raridade="Incomum"),
    "escudo_madeira_aço_rank_d": Equipamento("Escudo de Madeira e Aço (Rank D)", "Armadura", 160, bonus_defesa=10, peso=6.5, raridade="Incomum"),
    "proteção_perna_aço": Equipamento("Proteção de Perna de Aço", "Armadura", 105, bonus_defesa=5, peso=4.0, raridade="Incomum"),
    "braçadeiras_couro_ferro": Equipamento("Braçadeiras de Couro e Ferro", "Armadura", 75, bonus_defesa=3, peso=1.8, raridade="Incomum"),
    "gibão_pele_urso": Equipamento("Gibão de Pele de Urso", "Armadura", 150, bonus_defesa=7, peso=4.5, raridade="Incomum"),
    "escudo_cometa_mercenario": Equipamento("Escudo Cometa de Mercenário", "Armadura", 210, bonus_defesa=11, peso=7.5, raridade="Incomum"),
    "sobreveste_cavalaria": Equipamento("Sobreveste de Cavalaria", "Armadura", 130, bonus_defesa=6, peso=3.0, raridade="Incomum"),
    "elmo_normando_aço": Equipamento("Elmo Normando de Aço", "Armadura", 125, bonus_defesa=7, peso=3.0, raridade="Incomum"),
    "perneiras_placas_leves": Equipamento("Perneiras de Placas Leves", "Armadura", 140, bonus_defesa=6, peso=5.0, raridade="Incomum"),
    "peitoral_soldado_veterano": Equipamento("Peitoral de Soldado Veterano", "Armadura", 280, bonus_defesa=13, peso=11.0, raridade="Incomum"),
    "manoplas_aço_reforçado": Equipamento("Manoplas de Aço Reforçado", "Armadura", 115, bonus_defesa=4, peso=2.2, raridade="Incomum"),
    "botas_couro_militar": Equipamento("Botas de Couro Militar", "Armadura", 85, bonus_defesa=3, peso=1.5, raridade="Incomum"),
    "escudo_pavese_madeira": Equipamento("Escudo Pavese de Madeira", "Armadura", 190, bonus_defesa=10, peso=8.5, raridade="Incomum"),
    "elmo_visão_estreita": Equipamento("Elmo de Visão Estreita", "Armadura", 140, bonus_defesa=8, peso=4.0, raridade="Incomum"),
}

# --- ITENS GUERREIRO: RARO (Rank C) (01-50) ---
ITENS_GUERREIRO_RARO = {
    # ARMAS (Dano base: 25 a 35)
    "espada_aço_azul": Equipamento("Espada de Aço Azul", "Arma", 450, bonus_ataque=28, peso=2.2, raridade="Raro"),
    "machado_carrasco_real": Equipamento("Machado do Carrasco Real", "Arma", 520, bonus_ataque=32, peso=5.5, raridade="Raro"),
    "espada_montante_avalanche": Equipamento("Espada Montante Avalanche", "Arma", 600, bonus_ataque=35, peso=6.0, raridade="Raro"),
    "lança_presas_lobo": Equipamento("Lança Presas de Lobo", "Arma", 420, bonus_ataque=26, peso=3.0, raridade="Raro"),
    "maça_estrela_manhã_gélida": Equipamento("Estrela da Manhã Gélida", "Arma", 480, bonus_ataque=30, peso=4.5, raridade="Raro"),
    "espada_sangue_mercenario": Equipamento("Espada Sangue de Mercenário", "Arma", 470, bonus_ataque=29, peso=2.8, raridade="Raro"),
    "martelo_quebra_rochas": Equipamento("Martelo Quebra-Rochas", "Arma", 550, bonus_ataque=33, peso=7.0, raridade="Raro"),
    "alabarda_guarda_palacio": Equipamento("Alabarda da Guarda do Palácio", "Arma", 510, bonus_ataque=31, peso=5.2, raridade="Raro"),
    "espada_curta_obsidiana": Equipamento("Espada Curta de Obsidiana", "Arma", 400, bonus_ataque=25, peso=1.5, raridade="Raro"),
    "machado_fúria_nórdica": Equipamento("Machado da Fúria Nórdica", "Arma", 490, bonus_ataque=31, peso=4.8, raridade="Raro"),
    "espada_justiceira_rank_c": Equipamento("Espada Justiceira (Rank C)", "Arma", 530, bonus_ataque=32, peso=3.2, raridade="Raro"),
    "mangual_crânio_ferro": Equipamento("Mangual Crânio de Ferro", "Arma", 460, bonus_ataque=28, peso=4.0, raridade="Raro"),
    "lamina_vento_cortante": Equipamento("Lâmina do Vento Cortante", "Arma", 580, bonus_ataque=34, peso=1.8, raridade="Raro"),
    "espada_bastarda_cruzado": Equipamento("Espada Bastarda do Cruzado", "Arma", 540, bonus_ataque=33, peso=4.0, raridade="Raro"),
    "machado_duplo_minotauro": Equipamento("Machado Duplo de Minotauro", "Arma", 620, bonus_ataque=36, peso=8.0, raridade="Raro"),
    "espada_ferro_negro": Equipamento("Espada de Ferro Negro", "Arma", 440, bonus_ataque=27, peso=3.5, raridade="Raro"),
    "lança_serpente_aço": Equipamento("Lança Serpente de Aço", "Arma", 430, bonus_ataque=26, peso=2.8, raridade="Raro"),
    "martelo_punho_gigante": Equipamento("Martelo Punho de Gigante", "Arma", 590, bonus_ataque=34, peso=9.0, raridade="Raro"),
    "espada_falcão_prateado": Equipamento("Espada Falcão Prateado", "Arma", 500, bonus_ataque=30, peso=2.0, raridade="Raro"),
    "espada_pesada_rank_c": Equipamento("Espada Pesada (Rank C)", "Arma", 560, bonus_ataque=34, peso=5.5, raridade="Raro"),
    "gládio_centurião_elite": Equipamento("Gládio de Centurião de Elite", "Arma", 480, bonus_ataque=30, peso=2.4, raridade="Raro"),
    "espada_escamada_serpente": Equipamento("Espada Escamada de Serpente", "Arma", 495, bonus_ataque=31, peso=2.6, raridade="Raro"),
    "machado_viking_ancião": Equipamento("Machado Viking Ancião", "Arma", 515, bonus_ataque=32, peso=4.2, raridade="Raro"),
    "espada_chama_baixa": Equipamento("Espada de Chama Baixa", "Arma", 650, bonus_ataque=38, peso=3.0, raridade="Raro"),
    "alabarda_dragão_menor": Equipamento("Alabarda do Dragão Menor", "Arma", 630, bonus_ataque=37, peso=5.8, raridade="Raro"),

    # ARMADURAS (Defesa base: 20 a 35)
    "peitoral_aço_temperado": Equipamento("Peitoral de Aço Temperado", "Armadura", 700, bonus_defesa=25, peso=12.0, raridade="Raro"),
    "elmo_crina_cavalo": Equipamento("Elmo de Crina de Cavalo", "Armadura", 350, bonus_defesa=12, peso=3.0, raridade="Raro"),
    "escudo_brasão_leão": Equipamento("Escudo Brasão do Leão", "Armadura", 450, bonus_defesa=18, peso=7.0, raridade="Raro"),
    "manoplas_aço_negro": Equipamento("Manoplas de Ferro Negro", "Armadura", 300, bonus_defesa=10, peso=2.5, raridade="Raro"),
    "grevas_cavaleiro_andante": Equipamento("Grevas de Cavaleiro Andante", "Armadura", 320, bonus_defesa=11, peso=4.5, raridade="Raro"),
    "armadura_placas_meia": Equipamento("Meia Armadura de Placas", "Armadura", 850, bonus_defesa=28, peso=15.0, raridade="Raro"),
    "escudo_torre_vigia": Equipamento("Escudo Torre da Vigia", "Armadura", 550, bonus_defesa=22, peso=11.0, raridade="Raro"),
    "ombreiras_leão_dourado": Equipamento("Ombreiras do Leão Dourado", "Armadura", 280, bonus_defesa=9, peso=4.0, raridade="Raro"),
    "botas_aço_pesado_rank_c": Equipamento("Botas de Aço Pesado (Rank C)", "Armadura", 260, bonus_defesa=8, peso=3.0, raridade="Raro"),
    "elmo_grande_cruzado": Equipamento("Elmo Grande do Cruzado", "Armadura", 400, bonus_defesa=15, peso=4.0, raridade="Raro"),
    "cota_malha_mithril_falso": Equipamento("Cota de Malha de 'Mithril'", "Armadura", 900, bonus_defesa=30, peso=8.0, raridade="Raro"),
    "escudo_espinhos_ferro": Equipamento("Escudo de Espinhos de Ferro", "Armadura", 480, bonus_defesa=19, peso=8.0, raridade="Raro"),
    "peitoral_vanguarda_elite": Equipamento("Peitoral da Vanguarda de Elite", "Armadura", 780, bonus_defesa=27, peso=13.0, raridade="Raro"),
    "manoplas_esmagadoras": Equipamento("Manoplas Esmagadoras", "Armadura", 340, bonus_defesa=12, peso=3.5, raridade="Raro"),
    "perneiras_aço_azul": Equipamento("Perneiras de Aço Azul", "Armadura", 310, bonus_defesa=11, peso=5.0, raridade="Raro"),
    "escudo_redondo_valkiria": Equipamento("Escudo Redondo da Valquíria", "Armadura", 520, bonus_defesa=20, peso=6.0, raridade="Raro"),
    "elmo_chifres_touro": Equipamento("Elmo de Chifres de Touro", "Armadura", 380, bonus_defesa=14, peso=4.5, raridade="Raro"),
    "proteção_corpo_urso_cinzento": Equipamento("Proteção de Urso Cinzento", "Armadura", 600, bonus_defesa=22, peso=9.0, raridade="Raro"),
    "manoplas_escamadas_rank_c": Equipamento("Manoplas Escamadas (Rank C)", "Armadura", 320, bonus_defesa=11, peso=2.5, raridade="Raro"),
    "peitoral_couro_dragão_jovem": Equipamento("Peitoral de Couro de Dragão Jovem", "Armadura", 950, bonus_defesa=32, peso=6.0, raridade="Raro"),
    "escudo_muralha_ferro": Equipamento("Escudo Muralha de Ferro", "Armadura", 580, bonus_defesa=24, peso=12.0, raridade="Raro"),
    "botas_conquistador": Equipamento("Botas do Conquistador", "Armadura", 300, bonus_defesa=10, peso=3.5, raridade="Raro"),
    "elmo_visão_noturna": Equipamento("Elmo de Combate Noturno", "Armadura", 420, bonus_defesa=16, peso=3.8, raridade="Raro"),
    "ombreiras_espigadas_aço": Equipamento("Ombreiras Espigadas de Aço", "Armadura", 290, bonus_defesa=10, peso=4.5, raridade="Raro"),
    "armadura_placas_rank_c": Equipamento("Armadura de Placas (Rank C)", "Armadura", 1100, bonus_defesa=35, peso=18.0, raridade="Raro"),
}
# --- ITENS GUERREIRO: ÉPICO (Rank B) (01-50) ---
ITENS_GUERREIRO_EPICO = {
    # ARMAS (Dano base: 50 a 75)
    "espada_presagista_morte": Equipamento("Lâmina Presagista da Morte", "Arma", 1500, bonus_ataque=55, peso=2.5, raridade="Epico"),
    "machado_quebra_ceus": Equipamento("Machado Quebra-Céus", "Arma", 1800, bonus_ataque=62, peso=6.0, raridade="Epico"),
    "espada_sangue_valkiria": Equipamento("Sangue de Valquíria", "Arma", 2100, bonus_ataque=68, peso=3.0, raridade="Epico"),
    "lança_perfura_almas": Equipamento("Lança Perfura-Almas", "Arma", 1450, bonus_ataque=52, peso=3.2, raridade="Epico"),
    "maça_pilar_titã": Equipamento("Maça Pilar do Titã", "Arma", 1950, bonus_ataque=65, peso=9.5, raridade="Epico"),
    "espada_coração_ferro": Equipamento("Coração de Ferro (Rank B)", "Arma", 1700, bonus_ataque=58, peso=3.5, raridade="Epico"),
    "martelo_furia_vulcanica": Equipamento("Fúria Vulcânica", "Arma", 2200, bonus_ataque=72, peso=11.0, raridade="Epico"),
    "alabarda_eclipse": Equipamento("Alabarda do Eclipse Negro", "Arma", 1850, bonus_ataque=60, peso=5.5, raridade="Epico"),
    "espada_curta_estilhaço_estelar": Equipamento("Estilhaço Estelar", "Arma", 1400, bonus_ataque=50, peso=1.2, raridade="Epico"),
    "machado_uivo_lobo_branco": Equipamento("Uivo do Lobo Branco", "Arma", 1750, bonus_ataque=59, peso=5.0, raridade="Epico"),
    "espada_justiceira_imperial": Equipamento("Justiceira Imperial", "Arma", 2000, bonus_ataque=66, peso=4.0, raridade="Epico"),
    "mangual_terror_noturno": Equipamento("Terror Noturno", "Arma", 1600, bonus_ataque=56, peso=4.5, raridade="Epico"),
    "lamina_tempestade_aço": Equipamento("Lâmina da Tempestade", "Arma", 2300, bonus_ataque=74, peso=2.5, raridade="Epico"),
    "espada_bastarda_soberana": Equipamento("Bastarda do Soberano", "Arma", 2050, bonus_ataque=67, peso=4.2, raridade="Epico"),
    "machado_exterminador_gigantes": Equipamento("Exterminador de Gigantes", "Arma", 2400, bonus_ataque=75, peso=10.0, raridade="Epico"),
    "espada_obsidiana_ancestral": Equipamento("Obsidiana Ancestral", "Arma", 1550, bonus_ataque=54, peso=4.0, raridade="Epico"),
    "lança_cometa_escarlate": Equipamento("Cometa Escarlate", "Arma", 1650, bonus_ataque=57, peso=3.0, raridade="Epico"),
    "martelo_esmagador_mundos": Equipamento("Esmagador de Mundos", "Arma", 2350, bonus_ataque=73, peso=12.0, raridade="Epico"),
    "espada_preserva_honra": Equipamento("Preserva-Honra", "Arma", 1800, bonus_ataque=61, peso=3.0, raridade="Epico"),
    "espada_pesada_rank_b": Equipamento("Montante do General (Rank B)", "Arma", 2150, bonus_ataque=69, peso=7.5, raridade="Epico"),
    "gládio_conquistador_sangrento": Equipamento("Gládio do Conquistador", "Arma", 1750, bonus_ataque=59, peso=2.6, raridade="Epico"),
    "espada_divisor_montanhas": Equipamento("Divisor de Montanhas", "Arma", 2250, bonus_ataque=71, peso=8.0, raridade="Epico"),
    "machado_sangue_fervente": Equipamento("Sangue Fervente", "Arma", 1900, bonus_ataque=63, peso=5.0, raridade="Epico"),
    "espada_chama_eterna": Equipamento("Espada da Chama Eterna", "Arma", 2450, bonus_ataque=75, peso=3.5, raridade="Epico"),
    "alabarda_guarda_celestial": Equipamento("Alabarda da Guarda Celestial", "Arma", 2200, bonus_ataque=70, peso=6.0, raridade="Epico"),

    # ARMADURAS (Defesa base: 45 a 70)
    "peitoral_ouro_negro": Equipamento("Peitoral de Ouro Negro", "Armadura", 2500, bonus_defesa=55, peso=14.0, raridade="Epico"),
    "elmo_coroa_espinhas": Equipamento("Elmo Coroa de Espinhos", "Armadura", 1200, bonus_defesa=25, peso=3.5, raridade="Epico"),
    "escudo_vontade_ferro": Equipamento("Escudo Vontade de Ferro", "Armadura", 1800, bonus_defesa=40, peso=9.0, raridade="Epico"),
    "manoplas_toque_midas": Equipamento("Manoplas do Toque de Midas", "Armadura", 1100, bonus_defesa=22, peso=3.0, raridade="Epico"),
    "grevas_passos_gigante": Equipamento("Grevas Passos de Gigante", "Armadura", 1300, bonus_defesa=28, peso=5.5, raridade="Epico"),
    "armadura_placas_mithril": Equipamento("Placas de Mithril Puro", "Armadura", 3200, bonus_defesa=65, peso=9.0, raridade="Epico"),
    "escudo_fortaleza_movel": Equipamento("Fortaleza Móvel", "Armadura", 2200, bonus_defesa=48, peso=15.0, raridade="Epico"),
    "ombreiras_asas_fenix": Equipamento("Ombreiras Asas de Fênix", "Armadura", 1000, bonus_defesa=20, peso=4.5, raridade="Epico"),
    "botas_marcha_eterna": Equipamento("Botas da Marcha Eterna", "Armadura", 950, bonus_defesa=18, peso=3.0, raridade="Epico"),
    "elmo_cranio_dragão": Equipamento("Elmo de Crânio de Dragão", "Armadura", 1600, bonus_defesa=35, peso=5.0, raridade="Epico"),
    "armadura_escamas_quimera": Equipamento("Escamas de Quimera", "Armadura", 2800, bonus_defesa=60, peso=11.0, raridade="Epico"),
    "escudo_barreira_absoluta": Equipamento("Barreira Absoluta", "Armadura", 2400, bonus_defesa=52, peso=12.0, raridade="Epico"),
    "peitoral_vanguarda_imortal": Equipamento("Vanguarda do Imortal", "Armadura", 3000, bonus_defesa=62, peso=16.0, raridade="Epico"),
    "manoplas_forja_anã": Equipamento("Manoplas da Forja Anã", "Armadura", 1400, bonus_defesa=30, peso=4.0, raridade="Epico"),
    "perneiras_aço_astral": Equipamento("Perneiras de Aço Astral", "Armadura", 1250, bonus_defesa=27, peso=5.0, raridade="Epico"),
    "escudo_espelho_prata": Equipamento("Escudo Espelho de Prata", "Armadura", 1900, bonus_defesa=42, peso=7.0, raridade="Epico"),
    "elmo_furor_bestial": Equipamento("Elmo do Furor Bestial", "Armadura", 1500, bonus_defesa=32, peso=4.5, raridade="Epico"),
    "peitoral_couro_behemoth": Equipamento("Peitoral de Behemoth", "Armadura", 2600, bonus_defesa=58, peso=8.0, raridade="Epico"),
    "manoplas_punho_ferro_rank_b": Equipamento("Punho de Ferro (Rank B)", "Armadura", 1350, bonus_defesa=29, peso=3.5, raridade="Epico"),
    "peitoral_cristal_sangue": Equipamento("Peitoral de Cristal de Sangue", "Armadura", 3500, bonus_defesa=70, peso=10.0, raridade="Epico"),
    "escudo_egide_quebrada": Equipamento("Égide do Herói Caído", "Armadura", 2000, bonus_defesa=45, peso=10.0, raridade="Epico"),
    "botas_rastro_fogo": Equipamento("Botas Rastro de Fogo", "Armadura", 1100, bonus_defesa=24, peso=3.5, raridade="Epico"),
    "elmo_olhar_medusa": Equipamento("Elmo do Olhar de Pedra", "Armadura", 1700, bonus_defesa=38, peso=4.2, raridade="Epico"),
    "ombreiras_osso_ancião": Equipamento("Ombreiras de Osso Ancião", "Armadura", 1050, bonus_defesa=21, peso=5.0, raridade="Epico"),
    "armadura_placas_soberano": Equipamento("Placas do Soberano (Rank B)", "Armadura", 4000, bonus_defesa=75, peso=20.0, raridade="Epico"),
}

# --- ITENS GUERREIRO: LENDÁRIO (Rank A) (01-50) ---
ITENS_GUERREIRO_LENDARIO = {
    # ARMAS (Dano base: 110 a 160)
    "lamina_monarca_caos": Equipamento("Lâmina do Monarca do Caos", "Arma", 8000, bonus_ataque=135, peso=2.0, raridade="Lendario"),
    "machado_devorador_almas": Equipamento("Machado Devorador de Almas", "Arma", 7500, bonus_ataque=142, peso=5.5, raridade="Lendario"),
    "espada_mestre_kuran": Equipamento("Espada Longa de Kuran", "Arma", 9200, bonus_ataque=155, peso=3.0, raridade="Lendario"),
    "lança_soberano_mar": Equipamento("Lança do Soberano do Mar", "Arma", 6800, bonus_ataque=115, peso=3.2, raridade="Lendario"),
    "martelo_punicao_divina": Equipamento("Martelo da Punição Divina", "Arma", 8800, bonus_ataque=148, peso=10.0, raridade="Lendario"),
    "espada_cinzas_fenix": Equipamento("Lâmina das Cinzas da Fênix", "Arma", 8500, bonus_ataque=140, peso=2.5, raridade="Lendario"),
    "espada_presa_basilisco": Equipamento("Presa de Basilisco Real", "Arma", 7200, bonus_ataque=125, peso=1.5, raridade="Lendario"),
    "alabarda_general_sangrento": Equipamento("Alabarda do General Sangrento", "Arma", 7900, bonus_ataque=138, peso=5.8, raridade="Lendario"),
    "espada_corte_espacial": Equipamento("Espada do Corte Espacial", "Arma", 10500, bonus_ataque=160, peso=2.2, raridade="Lendario"),
    "machado_furia_behemoth": Equipamento("Fúria do Behemoth Ancião", "Arma", 8200, bonus_ataque=145, peso=7.0, raridade="Lendario"),
    "espada_bastarda_titan": Equipamento("Bastarda do Titã de Ferro", "Arma", 8600, bonus_ataque=144, peso=4.5, raridade="Lendario"),
    "mangual_estrela_cadente": Equipamento("Mangual Estrela Cadente", "Arma", 7400, bonus_ataque=130, peso=4.0, raridade="Lendario"),
    "lamina_tempestade_raio": Equipamento("Lâmina da Tempestade de Raios", "Arma", 9800, bonus_ataque=158, peso=2.0, raridade="Lendario"),
    "espada_soberania_rei": Equipamento("Espada da Soberania do Rei", "Arma", 9400, bonus_ataque=152, peso=3.5, raridade="Lendario"),
    "machado_exilado_infernal": Equipamento("Machado do Exilado Infernal", "Arma", 8900, bonus_ataque=150, peso=6.5, raridade="Lendario"),
    "espada_fragmento_lua": Equipamento("Fragmento da Lua de Sangue", "Arma", 7100, bonus_ataque=122, peso=3.8, raridade="Lendario"),
    "lança_perfuradora_céus": Equipamento("Lança Perfuradora de Céus", "Arma", 7800, bonus_ataque=136, peso=3.0, raridade="Lendario"),
    "martelo_tremor_terra": Equipamento("Martelo Tremor de Terra", "Arma", 9100, bonus_ataque=149, peso=12.0, raridade="Lendario"),
    "espada_maldita_orochi": Equipamento("Espada Maldita de Orochi", "Arma", 11000, bonus_ataque=165, peso=2.8, raridade="Lendario"),
    "montante_fogo_negro": Equipamento("Montante de Fogo Negro", "Arma", 9500, bonus_ataque=154, peso=8.0, raridade="Lendario"),
    "gládio_guerreiro_eterno": Equipamento("Gládio do Guerreiro Eterno", "Arma", 8300, bonus_ataque=141, peso=2.4, raridade="Lendario"),
    "espada_divisor_oceanos": Equipamento("Divisor de Oceanos", "Arma", 8700, bonus_ataque=146, peso=4.0, raridade="Lendario"),
    "machado_crânio_dragão": Equipamento("Machado de Crânio de Dragão", "Arma", 9000, bonus_ataque=151, peso=5.5, raridade="Lendario"),
    "espada_sol_da_meia_noite": Equipamento("Sol da Meia-Noite", "Arma", 10200, bonus_ataque=159, peso=3.0, raridade="Lendario"),
    "alabarda_sentinela_abissal": Equipamento("Alabarda Sentinela Abissal", "Arma", 8400, bonus_ataque=143, peso=6.0, raridade="Lendario"),

    # ARMADURAS (Defesa base: 90 a 130)
    "peitoral_monarca_sombra": Equipamento("Couraça do Monarca das Sombras", "Armadura", 12000, bonus_defesa=110, peso=10.0, raridade="Lendario"),
    "elmo_visão_deuses": Equipamento("Elmo da Visão dos Deuses", "Armadura", 5500, bonus_defesa=45, peso=3.0, raridade="Lendario"),
    "escudo_egide_suprema": Equipamento("Égide Suprema", "Armadura", 8500, bonus_defesa=85, peso=12.0, raridade="Lendario"),
    "manoplas_toque_vazio": Equipamento("Manoplas do Toque do Vazio", "Armadura", 4800, bonus_defesa=40, peso=2.5, raridade="Lendario"),
    "grevas_passos_de_ouro": Equipamento("Grevas de Passos de Ouro", "Armadura", 5200, bonus_defesa=42, peso=4.0, raridade="Lendario"),
    "armadura_placas_orichalcum": Equipamento("Armadura de Orichalcum", "Armadura", 15000, bonus_defesa=130, peso=14.0, raridade="Lendario"),
    "escudo_muralha_eterna": Equipamento("Muralha Eterna", "Armadura", 9000, bonus_defesa=95, peso=15.0, raridade="Lendario"),
    "ombreiras_grito_guerra": Equipamento("Ombreiras do Grito de Guerra", "Armadura", 4500, bonus_defesa=38, peso=4.0, raridade="Lendario"),
    "botas_viajante_dimensões": Equipamento("Botas do Viajante Dimensional", "Armadura", 4200, bonus_defesa=35, peso=2.0, raridade="Lendario"),
    "elmo_terror_asustador": Equipamento("Elmo do Terror Assustador", "Armadura", 5800, bonus_defesa=48, peso=4.0, raridade="Lendario"),
    "peitoral_escamas_leviatã": Equipamento("Peitoral de Escamas de Leviatã", "Armadura", 11000, bonus_defesa=105, peso=11.0, raridade="Lendario"),
    "escudo_sol_invicto": Equipamento("Escudo do Sol Invicto", "Armadura", 8200, bonus_defesa=80, peso=9.0, raridade="Lendario"),
    "armadura_vanguarda_astral": Equipamento("Vanguarda Astral", "Armadura", 13500, bonus_defesa=120, peso=12.0, raridade="Lendario"),
    "manoplas_punho_estelar": Equipamento("Manoplas do Punho Estelar", "Armadura", 5100, bonus_defesa=43, peso=3.0, raridade="Lendario"),
    "perneiras_aço_sagrado": Equipamento("Perneiras de Aço Sagrado", "Armadura", 4900, bonus_defesa=41, peso=5.0, raridade="Lendario"),
    "escudo_espelho_almas": Equipamento("Escudo Espelho de Almas", "Armadura", 7800, bonus_defesa=75, peso=8.0, raridade="Lendario"),
    "elmo_chifres_demoniacos": Equipamento("Elmo de Chifres Demoníacos", "Armadura", 6000, bonus_defesa=50, peso=5.0, raridade="Lendario"),
    "peitoral_sangue_dragão_ancião": Equipamento("Couraça de Sangue de Dragão", "Armadura", 14000, bonus_defesa=125, peso=13.0, raridade="Lendario"),
    "manoplas_quebra_ossos_lendaria": Equipamento("Manoplas Quebra-Ossos", "Armadura", 5400, bonus_defesa=44, peso=3.5, raridade="Lendario"),
    "peitoral_cristal_celeste": Equipamento("Peitoral de Cristal Celeste", "Armadura", 11500, bonus_defesa=108, peso=9.0, raridade="Lendario"),
    "escudo_titan_adaman": Equipamento("Escudo do Titã de Adamantio", "Armadura", 9800, bonus_defesa=100, peso=16.0, raridade="Lendario"),
    "botas_velocidade_luz": Equipamento("Botas da Velocidade da Luz", "Armadura", 4600, bonus_defesa=37, peso=1.5, raridade="Lendario"),
    "elmo_olho_ciclope": Equipamento("Elmo do Olho de Ciclope", "Armadura", 5700, bonus_defesa=47, peso=4.5, raridade="Lendario"),
    "ombreiras_feras_lendarias": Equipamento("Ombreiras das Feras Lendárias", "Armadura", 4300, bonus_defesa=36, peso=4.0, raridade="Lendario"),
    "armadura_cavaleiro_apocalipse": Equipamento("Armadura do Cavaleiro do Apocalipse", "Armadura", 16000, bonus_defesa=140, peso=18.0, raridade="Lendario"),
}

# --- ITENS GUERREIRO: MÍTICO (Rank S) (01-50) ---
ITENS_GUERREIRO_MITICO = {
    # ARMAS (Dano base: 200 a 350) - O poder de um Deus
    "lamina_kamish": Equipamento("Ira de Kamish", "Arma", 50000, bonus_ataque=320, peso=1.5, raridade="Mitico"),
    "espada_monarca_sombras": Equipamento("Espada do Monarca das Sombras", "Arma", 55000, bonus_ataque=350, peso=2.0, raridade="Mitico"),
    "machado_ragnarok": Equipamento("Ragnarok: O Fim dos Tempos", "Arma", 48000, bonus_ataque=310, peso=7.0, raridade="Mitico"),
    "lança_longinus_real": Equipamento("Lança de Longinus Original", "Arma", 45000, bonus_ataque=290, peso=3.0, raridade="Mitico"),
    "martelo_mjolnir_ancestral": Equipamento("Mjolnir Desperto", "Arma", 52000, bonus_ataque=330, peso=15.0, raridade="Mitico"),
    "espada_gram_mitica": Equipamento("Gram: A Matadora de Dragões", "Arma", 47000, bonus_ataque=300, peso=4.0, raridade="Mitico"),
    "lamina_vazio_eterno": Equipamento("Lâmina do Vazio Eterno", "Arma", 53000, bonus_ataque=340, peso=0.5, raridade="Mitico"),
    "alabarda_deus_guerra": Equipamento("Alabarda do Deus da Guerra", "Arma", 49000, bonus_ataque=315, peso=6.0, raridade="Mitico"),
    "espada_soberano_luz": Equipamento("Brilho do Soberano", "Arma", 54000, bonus_ataque=345, peso=2.5, raridade="Mitico"),
    "machado_leviatã_desperto": Equipamento("Machado Leviatã (Poder Total)", "Arma", 51000, bonus_ataque=325, peso=6.5, raridade="Mitico"),
    "espada_muramasa_amaldiçoada": Equipamento("Muramasa: A Devoradora de Almas", "Arma", 56000, bonus_ataque=360, peso=2.0, raridade="Mitico"),
    "mangual_supernova": Equipamento("Supernova", "Arma", 46000, bonus_ataque=295, peso=5.0, raridade="Mitico"),
    "espada_excalibur_verdadeira": Equipamento("Excalibur (Original)", "Arma", 60000, bonus_ataque=380, peso=3.0, raridade="Mitico"),
    "espada_caos_primordial": Equipamento("Lâmina do Caos Primordial", "Arma", 58000, bonus_ataque=370, peso=4.5, raridade="Mitico"),
    "machado_pangeia": Equipamento("Pangeia: O Divisor de Continentes", "Arma", 57000, bonus_ataque=365, peso=10.0, raridade="Mitico"),
    "espada_alma_dragão": Equipamento("Alma do Rei Dragão", "Arma", 54000, bonus_ataque=340, peso=3.0, raridade="Mitico"),
    "lança_odin_gungnir": Equipamento("Gungnir: A Lança Infalível", "Arma", 59000, bonus_ataque=375, peso=3.5, raridade="Mitico"),
    "martelo_destruidor_galáxias": Equipamento("Destruidor de Galáxias", "Arma", 62000, bonus_ataque=390, peso=18.0, raridade="Mitico"),
    "espada_crepusculo_deuses": Equipamento("Crepúsculo dos Deuses", "Arma", 65000, bonus_ataque=400, peso=3.0, raridade="Mitico"),
    "montante_atlas": Equipamento("Montante de Atlas", "Arma", 55000, bonus_ataque=355, peso=25.0, raridade="Mitico"),
    "gládio_imperador_eterno": Equipamento("Gládio do Imperador Eterno", "Arma", 51000, bonus_ataque=320, peso=2.0, raridade="Mitico"),
    "espada_eclipse_final": Equipamento("Eclipse Final", "Arma", 53000, bonus_ataque=335, peso=2.8, raridade="Mitico"),
    "machado_sangue_titã": Equipamento("Sangue de Titã", "Arma", 50000, bonus_ataque=320, peso=8.0, raridade="Mitico"),
    "espada_juizo_final": Equipamento("O Juízo Final", "Arma", 68000, bonus_ataque=420, peso=3.5, raridade="Mitico"),
    "alabarda_infinito": Equipamento("Alabarda do Infinito", "Arma", 63000, bonus_ataque=385, peso=5.0, raridade="Mitico"),

    # ARMADURAS (Defesa base: 180 a 300)
    "peitoral_soberano_morte": Equipamento("Couraça do Soberano da Morte", "Armadura", 80000, bonus_defesa=250, peso=12.0, raridade="Mitico"),
    "elmo_olho_deus": Equipamento("Olho de Deus (Omnisciência)", "Armadura", 40000, bonus_defesa=100, peso=2.0, raridade="Mitico"),
    "escudo_egide_verdadeira": Equipamento("Égide de Atena (Original)", "Armadura", 60000, bonus_defesa=180, peso=10.0, raridade="Mitico"),
    "manoplas_destruição_universo": Equipamento("Manoplas da Destruição", "Armadura", 45000, bonus_defesa=90, peso=3.0, raridade="Mitico"),
    "grevas_mensageiro_deuses": Equipamento("Grevas de Hermes", "Armadura", 42000, bonus_defesa=85, peso=1.0, raridade="Mitico"),
    "armadura_adamantio_puro": Equipamento("Armadura de Adamantio Divino", "Armadura", 90000, bonus_defesa=280, peso=15.0, raridade="Mitico"),
    "escudo_muralha_asgard": Equipamento("Muralha de Asgard", "Armadura", 65000, bonus_defesa=200, peso=20.0, raridade="Mitico"),
    "ombreiras_titan_atlas": Equipamento("Ombreiras de Atlas", "Armadura", 38000, bonus_defesa=80, peso=10.0, raridade="Mitico"),
    "botas_onipresença": Equipamento("Botas da Onipresença", "Armadura", 48000, bonus_defesa=95, peso=0.5, raridade="Mitico"),
    "elmo_coroa_monarca": Equipamento("Coroa do Monarca Final", "Armadura", 55000, bonus_defesa=120, peso=3.0, raridade="Mitico"),
    "peitoral_coração_estrela": Equipamento("Coração de uma Estrela Morta", "Armadura", 85000, bonus_defesa=260, peso=5.0, raridade="Mitico"),
    "escudo_esplendor_solar": Equipamento("Esplendor de Rá", "Armadura", 62000, bonus_defesa=190, peso=8.0, raridade="Mitico"),
    "armadura_vanguarda_deuses": Equipamento("Vanguarda dos Deuses", "Armadura", 95000, bonus_defesa=290, peso=14.0, raridade="Mitico"),
    "manoplas_zero_absoluto": Equipamento("Punhos do Zero Absoluto", "Armadura", 44000, bonus_defesa=95, peso=2.5, raridade="Mitico"),
    "perneiras_indestrutíveis": Equipamento("Perneiras do Inabalável", "Armadura", 41000, bonus_defesa=88, peso=6.0, raridade="Mitico"),
    "escudo_espelho_verdade": Equipamento("Espelho da Verdade Divina", "Armadura", 58000, bonus_defesa=175, peso=7.0, raridade="Mitico"),
    "elmo_furia_zeus": Equipamento("Elmo do Trovão de Zeus", "Armadura", 50000, bonus_defesa=110, peso=4.0, raridade="Mitico"),
    "peitoral_dragão_apocalipse": Equipamento("Escamas do Dragão do Apocalipse", "Armadura", 100000, bonus_defesa=300, peso=10.0, raridade="Mitico"),
    "manoplas_toque_deus": Equipamento("Toque da Divindade", "Armadura", 47000, bonus_defesa=100, peso=2.0, raridade="Mitico"),
    "peitoral_vontade_cosmos": Equipamento("Vontade do Cosmos", "Armadura", 92000, bonus_defesa=275, peso=8.0, raridade="Mitico"),
    "escudo_origem_mundo": Equipamento("O Primeiro Escudo", "Armadura", 70000, bonus_defesa=210, peso=12.0, raridade="Mitico"),
    "botas_passo_celestial": Equipamento("Passo do Firmamento", "Armadura", 43000, bonus_defesa=90, peso=1.5, raridade="Mitico"),
    "elmo_vazio_infinito": Equipamento("Mascara do Vazio Infinito", "Armadura", 52000, bonus_defesa=115, peso=1.0, raridade="Mitico"),
    "ombreiras_universo": Equipamento("Ombreiras do Firmamento", "Armadura", 39000, bonus_defesa=85, peso=5.0, raridade="Mitico"),
    "armadura_entidade_suprema": Equipamento("Avatar da Entidade Suprema", "Armadura", 120000, bonus_defesa=350, peso=10.0, raridade="Mitico"),
}