#arquivo dos itens de assasinos

from Itens import Equipamento

# --- ITENS ASSASSINO: COMUM (Rank E) (01-50) ---
ITENS_ASSASSINO_COMUM = {
    # ARMAS (Dano base: 3 a 9 | Peso: 0.2 a 0.8)
    "adaga_ferrugem": Equipamento("Adaga Enferrujada", "Arma", 15, bonus_ataque=3, peso=0.4, raridade="Comum"),
    "faca_arremesso_cega": Equipamento("Faca de Arremesso Cega", "Arma", 10, bonus_ataque=2, peso=0.2, raridade="Comum"),
    "punhal_madeira_treino": Equipamento("Punhal de Treino", "Arma", 8, bonus_ataque=2, peso=0.3, raridade="Comum"),
    "estilete_ferro_pobre": Equipamento("Estilete de Ferro Pobre", "Arma", 20, bonus_ataque=4, peso=0.3, raridade="Comum"),
    "lamina_oculta_gasta": Equipamento("Lâmina Oculta Gasta", "Arma", 35, bonus_ataque=5, peso=0.5, raridade="Comum"),
    "kama_bronze_velha": Equipamento("Kama de Bronze Velha", "Arma", 30, bonus_ataque=5, peso=0.7, raridade="Comum"),
    "shuriken_ferro_lascado": Equipamento("Shuriken Lascada", "Arma", 12, bonus_ataque=3, peso=0.1, raridade="Comum"),
    "faca_osso_pequena": Equipamento("Faca de Osso Pequena", "Arma", 18, bonus_ataque=4, peso=0.3, raridade="Comum"),
    "garra_ferro_simples": Equipamento("Garra de Ferro Simples", "Arma", 40, bonus_ataque=6, peso=0.6, raridade="Comum"),
    "adaga_recruta_rank_e": Equipamento("Adaga de Recruta (Rank E)", "Arma", 45, bonus_ataque=7, peso=0.4, raridade="Comum"),
    "punhal_serrilhado_quebrado": Equipamento("Punhal Serrilhado Quebrado", "Arma", 25, bonus_ataque=5, peso=0.4, raridade="Comum"),
    "lamina_dedo_discreta": Equipamento("Lâmina de Dedo Discreta", "Arma", 22, bonus_ataque=4, peso=0.1, raridade="Comum"),
    "faca_caçador_novato": Equipamento("Faca de Caçador Novato", "Arma", 38, bonus_ataque=6, peso=0.5, raridade="Comum"),
    "adaga_estripadora_velha": Equipamento("Adaga Estripadora Velha", "Arma", 42, bonus_ataque=7, peso=0.5, raridade="Comum"),
    "agulha_combate_ferro": Equipamento("Agulha de Combate de Ferro", "Arma", 28, bonus_ataque=5, peso=0.1, raridade="Comum"),
    "tantō_madeira_treino": Equipamento("Tantō de Treino", "Arma", 15, bonus_ataque=3, peso=0.4, raridade="Comum"),
    "punhal_boca_sapo": Equipamento("Punhal de Beco", "Arma", 20, bonus_ataque=4, peso=0.3, raridade="Comum"),
    "faca_arremesso_ferro": Equipamento("Faca de Arremesso de Ferro", "Arma", 15, bonus_ataque=3, peso=0.2, raridade="Comum"),
    "adaga_viagem_simples": Equipamento("Adaga de Viagem Simples", "Arma", 32, bonus_ataque=6, peso=0.4, raridade="Comum"),
    "lamina_curta_podre": Equipamento("Lâmina Curta Podre", "Arma", 10, bonus_ataque=2, peso=0.4, raridade="Comum"),
    "garra_gato_ferrugem": Equipamento("Garra de Gato Enferrujada", "Arma", 35, bonus_ataque=5, peso=0.5, raridade="Comum"),
    "faca_carniceiro_pequena": Equipamento("Faca de Carniceiro Pequena", "Arma", 25, bonus_ataque=4, peso=0.6, raridade="Comum"),
    "punhal_silencioso_pobre": Equipamento("Punhal Silencioso Pobre", "Arma", 30, bonus_ataque=5, peso=0.3, raridade="Comum"),
    "shuriken_ponta_dupla": Equipamento("Shuriken de Ponta Dupla", "Arma", 18, bonus_ataque=3, peso=0.1, raridade="Comum"),
    "adaga_lascada_rank_e": Equipamento("Adaga Lascada (Rank E)", "Arma", 14, bonus_ataque=3, peso=0.4, raridade="Comum"),

    # ARMADURAS (Defesa base: 1 a 5 | Peso: 0.1 a 1.5)
    "capuz_tecido_sujo": Equipamento("Capuz de Tecido Sujo", "Armadura", 12, bonus_defesa=1, peso=0.2, raridade="Comum"),
    "tunica_couro_fina": Equipamento("Túnica de Couro Fina", "Armadura", 50, bonus_defesa=3, peso=1.5, raridade="Comum"),
    "botas_pano_velhas": Equipamento("Botas de Pano Velhas", "Armadura", 20, bonus_defesa=1, peso=0.4, raridade="Comum"),
    "luvas_dedo_cortado": Equipamento("Luvas de Dedo Cortado", "Armadura", 15, bonus_defesa=1, peso=0.2, raridade="Comum"),
    "mascara_tecido_preto": Equipamento("Máscara de Tecido Preto", "Armadura", 25, bonus_defesa=1, peso=0.1, raridade="Comum"),
    "braçadeiras_couro_cru": Equipamento("Braçadeiras de Couro Cru", "Armadura", 30, bonus_defesa=2, peso=0.5, raridade="Comum"),
    "cinto_adagas_gasto": Equipamento("Cinto de Adagas Gasto", "Armadura", 18, bonus_defesa=1, peso=0.3, raridade="Comum"),
    "manto_nevoa_pobre": Equipamento("Manto da Névoa Pobre", "Armadura", 65, bonus_defesa=4, peso=1.0, raridade="Comum"),
    "perneiras_tecido_escuro": Equipamento("Perneiras de Tecido Escuro", "Armadura", 40, bonus_defesa=2, peso=0.8, raridade="Comum"),
    "colete_couro_remendado": Equipamento("Colete de Couro Remendado", "Armadura", 45, bonus_defesa=3, peso=1.2, raridade="Comum"),
    "mascara_gazueira_velha": Equipamento("Máscara de Gazueira Velha", "Armadura", 22, bonus_defesa=1, peso=0.1, raridade="Comum"),
    "botas_couro_macio": Equipamento("Botas de Couro Macio", "Armadura", 38, bonus_defesa=2, peso=0.5, raridade="Comum"),
    "capa_trapos_noturnos": Equipamento("Capa de Trapos Noturnos", "Armadura", 20, bonus_defesa=1, peso=0.6, raridade="Comum"),
    "bracelete_corda_trançada": Equipamento("Bracelete de Corda", "Armadura", 8, bonus_defesa=1, peso=0.1, raridade="Comum"),
    "colete_tecido_grosso": Equipamento("Colete de Tecido Grosso", "Armadura", 42, bonus_defesa=3, peso=1.0, raridade="Comum"),
    "luvas_assaltante_usadas": Equipamento("Luvas de Assaltante Usadas", "Armadura", 25, bonus_defesa=2, peso=0.2, raridade="Comum"),
    "bandana_sombria_rank_e": Equipamento("Bandana Sombria (Rank E)", "Armadura", 15, bonus_defesa=1, peso=0.1, raridade="Comum"),
    "perneiras_pano_reforçado": Equipamento("Perneiras de Pano Reforçado", "Armadura", 35, bonus_defesa=2, peso=0.7, raridade="Comum"),
    "ombreira_couro_unica": Equipamento("Ombreira de Couro Única", "Armadura", 28, bonus_defesa=2, peso=0.5, raridade="Comum"),
    "tunica_camuflagem_simples": Equipamento("Túnica de Camuflagem Simples", "Armadura", 55, bonus_defesa=3, peso=1.1, raridade="Comum"),
    "sapatos_sola_borracha": Equipamento("Sapatos de Sola de Borracha", "Armadura", 30, bonus_defesa=1, peso=0.4, raridade="Comum"),
    "proteção_pulso_couro": Equipamento("Proteção de Pulso de Couro", "Armadura", 15, bonus_defesa=1, peso=0.2, raridade="Comum"),
    "capuz_ladino_rank_e": Equipamento("Capuz de Ladino (Rank E)", "Armadura", 40, bonus_defesa=2, peso=0.3, raridade="Comum"),
    "saia_combate_leve": Equipamento("Saia de Combate Leve", "Armadura", 32, bonus_defesa=2, peso=0.6, raridade="Comum"),
    "colete_assassino_noviço": Equipamento("Colete de Noviço", "Armadura", 60, bonus_defesa=5, peso=1.3, raridade="Comum"),
}

# --- ITENS ASSASSINO: INCOMUM (Rank D) (01-50) ---
ITENS_ASSASSINO_INCOMUM = {
    # ARMAS (Ataque) (25 itens) - Dano base: 10 a 18
    "adaga_aço_negro": Equipamento("Adaga de Aço Negro", "Arma", 150, bonus_ataque=12, peso=0.4, raridade="Incomum"),
    "sai_ferro_polido": Equipamento("Sai de Ferro Polido", "Arma", 130, bonus_ataque=11, peso=0.6, raridade="Incomum"),
    "adaga_aprendiz_assassino": Equipamento("Adaga de Aprendiz (Rank D)", "Arma", 180, bonus_ataque=14, peso=0.4, raridade="Incomum"),
    "faca_caçador_selvagem": Equipamento("Faca do Caçador Selvagem", "Arma", 160, bonus_ataque=13, peso=0.5, raridade="Incomum"),
    "punhal_venenoso_estagio1": Equipamento("Punhal de Veneno Lento", "Arma", 210, bonus_ataque=15, peso=0.4, raridade="Incomum"),
    "tanto_aço_temperado": Equipamento("Tantō de Aço Temperado", "Arma", 190, bonus_ataque=14, peso=0.5, raridade="Incomum"),
    "garra_lobo_ferro": Equipamento("Garras de Lobo de Ferro", "Arma", 175, bonus_ataque=13, peso=0.8, raridade="Incomum"),
    "lamina_curva_deserto": Equipamento("Lâmina Curva do Deserto", "Arma", 200, bonus_ataque=16, peso=0.6, raridade="Incomum"),
    "shuriken_aço_grande": Equipamento("Shuriken de Aço Grande", "Arma", 120, bonus_ataque=10, peso=0.2, raridade="Incomum"),
    "adagas_gemeas_mercenario": Equipamento("Adagas Gêmeas de Mercenário", "Arma", 250, bonus_ataque=18, peso=0.8, raridade="Incomum"),
    "estilete_perfurador_aço": Equipamento("Estilete Perfurador de Aço", "Arma", 145, bonus_ataque=13, peso=0.3, raridade="Incomum"),
    "faca_obsidiana_afiada": Equipamento("Faca de Obsidiana Afiada", "Arma", 170, bonus_ataque=15, peso=0.5, raridade="Incomum"),
    "adaga_presa_serpente": Equipamento("Presa de Serpente (Rank D)", "Arma", 195, bonus_ataque=16, peso=0.4, raridade="Incomum"),
    "kunai_militar_aço": Equipamento("Kunai Militar de Aço", "Arma", 135, bonus_ataque=11, peso=0.2, raridade="Incomum"),
    "lamina_pulso_mecanica": Equipamento("Lâmina de Pulso Mecânica", "Arma", 230, bonus_ataque=18, peso=0.5, raridade="Incomum"),
    "faca_osso_ancião": Equipamento("Faca de Osso Ancião", "Arma", 175, bonus_ataque=15, peso=0.6, raridade="Incomum"),
    "punhal_luz_opaca": Equipamento("Punhal de Luz Opaca", "Arma", 165, bonus_ataque=14, peso=0.4, raridade="Incomum"),
    "adaga_aço_azul_d": Equipamento("Adaga de Aço Azul (Rank D)", "Arma", 220, bonus_ataque=17, peso=0.4, raridade="Incomum"),
    "faca_corte_preciso": Equipamento("Faca de Corte Preciso", "Arma", 155, bonus_ataque=13, peso=0.4, raridade="Incomum"),
    "garra_sombra_ferro": Equipamento("Garra da Sombra de Ferro", "Arma", 180, bonus_ataque=15, peso=0.6, raridade="Incomum"),
    "punhal_marfim_negro": Equipamento("Punhal de Marfim Negro", "Arma", 205, bonus_ataque=16, peso=0.4, raridade="Incomum"),
    "lamina_silenciosa_aço": Equipamento("Lâmina Silenciosa", "Arma", 190, bonus_ataque=15, peso=0.5, raridade="Incomum"),
    "faca_arremesso_balanceada": Equipamento("Faca de Arremesso Balanceada", "Arma", 130, bonus_ataque=11, peso=0.2, raridade="Incomum"),
    "adaga_mestre_esgrima": Equipamento("Adaga de Esgrima Curta", "Arma", 215, bonus_ataque=17, peso=0.6, raridade="Incomum"),
    "faca_ritual_antigo": Equipamento("Faca de Ritual Antigo", "Arma", 140, bonus_ataque=12, peso=0.5, raridade="Incomum"),

    # ARMADURAS (Defesa) (25 itens) - Defesa base: 6 a 12
    "traje_couro_ajustado": Equipamento("Traje de Couro Ajustado", "Armadura", 220, bonus_defesa=8, peso=2.0, raridade="Incomum"),
    "capuz_assassino_d": Equipamento("Capuz de Assassino (Rank D)", "Armadura", 140, bonus_defesa=6, peso=0.3, raridade="Incomum"),
    "botas_passo_leve": Equipamento("Botas de Passo Leve", "Armadura", 130, bonus_defesa=5, peso=0.5, raridade="Incomum"),
    "manoplas_couro_reforçado": Equipamento("Manoplas de Couro Reforçado", "Armadura", 110, bonus_defesa=5, peso=0.6, raridade="Incomum"),
    "mascara_ferro_parcial": Equipamento("Máscara de Ferro Parcial", "Armadura", 160, bonus_defesa=7, peso=0.8, raridade="Incomum"),
    "manto_sombra_d": Equipamento("Manto das Sombras (Rank D)", "Armadura", 280, bonus_defesa=10, peso=1.2, raridade="Incomum"),
    "ombreiras_couro_negro": Equipamento("Ombreiras de Couro Negro", "Armadura", 120, bonus_defesa=5, peso=0.8, raridade="Incomum"),
    "cinto_alquimia_veneno": Equipamento("Cinto de Alquimia de Veneno", "Armadura", 150, bonus_defesa=4, peso=0.5, raridade="Incomum"),
    "colete_malha_fina": Equipamento("Colete de Malha Fina", "Armadura", 350, bonus_defesa=12, peso=4.0, raridade="Incomum"),
    "luvas_toque_fantasma": Equipamento("Luvas do Toque Fantasma", "Armadura", 180, bonus_defesa=6, peso=0.3, raridade="Incomum"),
    "botas_silencio_noturno": Equipamento("Botas do Silêncio Noturno", "Armadura", 195, bonus_defesa=7, peso=0.6, raridade="Incomum"),
    "mascara_sorriso_oculto": Equipamento("Máscara do Sorriso Oculto", "Armadura", 175, bonus_defesa=6, peso=0.2, raridade="Incomum"),
    "perneiras_agilidade_d": Equipamento("Perneiras de Agilidade (Rank D)", "Armadura", 210, bonus_defesa=9, peso=1.1, raridade="Incomum"),
    "braçadeiras_estilete_escondido": Equipamento("Braçadeiras com Coldre", "Armadura", 190, bonus_defesa=7, peso=0.7, raridade="Incomum"),
    "manto_nevoa_noturna": Equipamento("Manto da Névoa Noturna", "Armadura", 300, bonus_defesa=11, peso=1.3, raridade="Incomum"),
    "luvas_precisao_d": Equipamento("Luvas de Precisão (Rank D)", "Armadura", 155, bonus_defesa=6, peso=0.3, raridade="Incomum"),
    "tunica_assassino_noviço": Equipamento("Túnica de Noviço", "Armadura", 240, bonus_defesa=9, peso=1.6, raridade="Incomum"),
    "proteção_pescoço_couro": Equipamento("Proteção de Pescoço de Couro", "Armadura", 115, bonus_defesa=4, peso=0.4, raridade="Incomum"),
    "botas_atracagem_silenciosa": Equipamento("Botas de Atracagem Silenciosa", "Armadura", 165, bonus_defesa=6, peso=0.6, raridade="Incomum"),
    "cinto_utilitario_incomum": Equipamento("Cinto Utilitário (Rank D)", "Armadura", 140, bonus_defesa=5, peso=0.5, raridade="Incomum"),
    "colete_couro_tachonado_leve": Equipamento("Colete Tachonado Leve", "Armadura", 290, bonus_defesa=10, peso=2.5, raridade="Incomum"),
    "capuz_olhar_vazio": Equipamento("Capuz do Olhar Vazio", "Armadura", 185, bonus_defesa=7, peso=0.3, raridade="Incomum"),
    "braçadeiras_escalada": Equipamento("Braçadeiras de Escalador", "Armadura", 130, bonus_defesa=5, peso=0.6, raridade="Incomum"),
    "manto_camuflagem_floresta": Equipamento("Manto Camuflagem Florestal", "Armadura", 270, bonus_defesa=9, peso=1.1, raridade="Incomum"),
    "armadura_leve_corvo": Equipamento("Armadura Leve do Corvo", "Armadura", 320, bonus_defesa=11, peso=3.5, raridade="Incomum"),
}

# --- ITENS ASSASSINO: RARO (Rank C) (01-50) ---
ITENS_ASSASSINO_RARO = {
    # ARMAS (Ataque) (25 itens) - Dano base: 25 a 40
    "adaga_ferro_negro": Equipamento("Adaga de Ferro Negro", "Arma", 450, bonus_ataque=28, peso=0.4, raridade="Raro"),
    "punhal_misericordia": Equipamento("Punhal da Misericórdia", "Arma", 480, bonus_ataque=31, peso=0.3, raridade="Raro"),
    "lamina_sombra_corrompida": Equipamento("Lâmina da Sombra Corrompida", "Arma", 550, bonus_ataque=35, peso=0.4, raridade="Raro"),
    "garra_pantera_negra": Equipamento("Garras de Pantera Negra", "Arma", 520, bonus_ataque=33, peso=0.7, raridade="Raro"),
    "adaga_presa_vibrant": Equipamento("Presa Vibrante", "Arma", 500, bonus_ataque=32, peso=0.3, raridade="Raro"),
    "espada_curta_assassino_elite": Equipamento("Espada Curta de Elite", "Arma", 580, bonus_ataque=36, peso=1.2, raridade="Raro"),
    "punhal_veneno_paralisante": Equipamento("Punhal de Veneno Paralisante", "Arma", 620, bonus_ataque=38, peso=0.4, raridade="Raro"),
    "kama_aço_azul": Equipamento("Kama de Aço Azul", "Arma", 490, bonus_ataque=31, peso=0.8, raridade="Raro"),
    "shuriken_vórtice_aço": Equipamento("Shuriken Vórtice de Aço", "Arma", 420, bonus_ataque=26, peso=0.2, raridade="Raro"),
    "lamina_oculta_mecanismo_c": Equipamento("Lâmina Oculta Avançada (Rank C)", "Arma", 600, bonus_ataque=37, peso=0.5, raridade="Raro"),
    "adaga_cristal_sangue": Equipamento("Adaga de Cristal de Sangue", "Arma", 650, bonus_ataque=39, peso=0.3, raridade="Raro"),
    "estilete_perfura_malha": Equipamento("Estilete Perfura-Malha", "Arma", 470, bonus_ataque=29, peso=0.2, raridade="Raro"),
    "faca_arremesso_precisão_c": Equipamento("Faca de Arremesso de Precisão", "Arma", 440, bonus_ataque=27, peso=0.2, raridade="Raro"),
    "punhal_coração_gélido": Equipamento("Punhal Coração Gélido", "Arma", 530, bonus_ataque=34, peso=0.4, raridade="Raro"),
    "garra_escorpião_rei": Equipamento("Garra de Escorpião Rei", "Arma", 610, bonus_ataque=37, peso=0.8, raridade="Raro"),
    "tanto_mestre_ninja": Equipamento("Tantō do Mestre Ninja", "Arma", 590, bonus_ataque=36, peso=0.5, raridade="Raro"),
    "adaga_dente_de_sabre": Equipamento("Adaga Dente de Sabre", "Arma", 540, bonus_ataque=34, peso=0.6, raridade="Raro"),
    "lamina_dual_cruzada": Equipamento("Lâminas Dual Cruzadas", "Arma", 630, bonus_ataque=38, peso=1.0, raridade="Raro"),
    "punhal_sopro_morte": Equipamento("Punhal Sopro da Morte", "Arma", 570, bonus_ataque=35, peso=0.3, raridade="Raro"),
    "faca_selva_reforçada": Equipamento("Faca de Selva Reforçada", "Arma", 460, bonus_ataque=28, peso=0.7, raridade="Raro"),
    "adaga_mergulho_sombrio": Equipamento("Adaga Mergulho Sombrio", "Arma", 510, bonus_ataque=32, peso=0.4, raridade="Raro"),
    "kunai_explosiva_fraca": Equipamento("Kunai de Impacto (Rank C)", "Arma", 480, bonus_ataque=30, peso=0.3, raridade="Raro"),
    "lamina_leque_ferro": Equipamento("Lâmina Leque de Ferro", "Arma", 450, bonus_ataque=28, peso=0.4, raridade="Raro"),
    "adaga_obsidiana_lapidada": Equipamento("Adaga de Obsidiana Lapidada", "Arma", 560, bonus_ataque=35, peso=0.5, raridade="Raro"),
    "lamina_caçador_recompensa": Equipamento("Lâmina do Caçador de Recompensa", "Arma", 640, bonus_ataque=40, peso=0.6, raridade="Raro"),

    # ARMADURAS (Defesa) (25 itens) - Defesa base: 18 a 32
    "traje_assassino_noturno": Equipamento("Traje do Assassino Noturno", "Armadura", 800, bonus_defesa=24, peso=2.2, raridade="Raro"),
    "capuz_executor_rank_c": Equipamento("Capuz do Executor (Rank C)", "Armadura", 350, bonus_defesa=12, peso=0.4, raridade="Raro"),
    "botas_passada_silenciosa": Equipamento("Botas da Passada Silenciosa", "Armadura", 320, bonus_defesa=10, peso=0.5, raridade="Raro"),
    "luvas_toque_mortal": Equipamento("Luvas do Toque Mortal", "Armadura", 300, bonus_defesa=9, peso=0.3, raridade="Raro"),
    "mascara_fantasma_opera": Equipamento("Máscara do Fantasma", "Armadura", 380, bonus_defesa=13, peso=0.2, raridade="Raro"),
    "manto_invisibilidade_baixa": Equipamento("Manto da Penumbra", "Armadura", 950, bonus_defesa=28, peso=1.0, raridade="Raro"),
    "peitoral_couro_behemoth_jovem": Equipamento("Peitoral de Couro de Fera", "Armadura", 850, bonus_defesa=26, peso=3.5, raridade="Raro"),
    "braçadeiras_laminadas_c": Equipamento("Braçadeiras Laminadas", "Armadura", 310, bonus_defesa=11, peso=0.8, raridade="Raro"),
    "cinto_utilitario_mestre": Equipamento("Cinto de Mestre Assassino", "Armadura", 280, bonus_defesa=8, peso=0.6, raridade="Raro"),
    "ombreiras_corvo_negro": Equipamento("Ombreiras do Corvo Negro", "Armadura", 290, bonus_defesa=10, peso=0.7, raridade="Raro"),
    "botas_agilidade_suprema": Equipamento("Botas de Agilidade Suprema", "Armadura", 340, bonus_defesa=12, peso=0.5, raridade="Raro"),
    "mascara_respiração_filtrada": Equipamento("Máscara Alquímica", "Armadura", 400, bonus_defesa=14, peso=0.4, raridade="Raro"),
    "perneiras_escamadas_leves": Equipamento("Perneiras Escamadas Leves", "Armadura", 360, bonus_defesa=13, peso=1.2, raridade="Raro"),
    "tunica_manto_noturno_c": Equipamento("Túnica Manto Noturno (Rank C)", "Armadura", 780, bonus_defesa=23, peso=1.8, raridade="Raro"),
    "luvas_escalada_mestre": Equipamento("Luvas de Escalada Profissional", "Armadura", 320, bonus_defesa=11, peso=0.3, raridade="Raro"),
    "ombreiras_ocultação_sombra": Equipamento("Ombreiras de Ocultação", "Armadura", 330, bonus_defesa=12, peso=0.9, raridade="Raro"),
    "colete_couro_serpente": Equipamento("Colete de Couro de Serpente", "Armadura", 820, bonus_defesa=25, peso=2.0, raridade="Raro"),
    "elmo_leve_sombra": Equipamento("Elmo Leve da Sombra", "Armadura", 370, bonus_defesa=13, peso=0.8, raridade="Raro"),
    "braçadeiras_aço_azul_c": Equipamento("Braçadeiras de Aço Azul", "Armadura", 340, bonus_defesa=12, peso=0.7, raridade="Raro"),
    "manto_nevoa_espessa": Equipamento("Manto da Névoa Espessa", "Armadura", 900, bonus_defesa=27, peso=1.1, raridade="Raro"),
    "botas_rastro_invisivel": Equipamento("Botas do Rastro Invisível", "Armadura", 380, bonus_defesa=14, peso=0.4, raridade="Raro"),
    "cinto_adagas_infinitas": Equipamento("Cinto de Suporte de Adagas", "Armadura", 300, bonus_defesa=9, peso=0.6, raridade="Raro"),
    "mascara_oni_rank_c": Equipamento("Máscara Oni (Rank C)", "Armadura", 420, bonus_defesa=15, peso=0.5, raridade="Raro"),
    "proteção_peito_reforçada_c": Equipamento("Proteção de Peito Reforçada", "Armadura", 700, bonus_defesa=22, peso=2.8, raridade="Raro"),
    "traje_mimetismo_urbano": Equipamento("Traje de Mimetismo", "Armadura", 1100, bonus_defesa=32, peso=1.5, raridade="Raro"),
}

# --- ITENS ASSASSINO: ÉPICO (Rank B) (01-50) ---
ITENS_ASSASSINO_EPICO = {
    # ARMAS (Ataque) (25 itens) - Dano base: 50 a 80
    "lamina_presagista_noite": Equipamento("Lâmina Presagista da Noite", "Arma", 1600, bonus_ataque=55, peso=0.4, raridade="Epico"),
    "adaga_presa_hidra": Equipamento("Presa de Hidra Venenosa", "Arma", 1850, bonus_ataque=62, peso=0.3, raridade="Epico"),
    "punhal_beijo_viuva": Equipamento("Beijo da Viúva Negra", "Arma", 2100, bonus_ataque=68, peso=0.2, raridade="Epico"),
    "garra_tigre_branco_b": Equipamento("Garras do Tigre Branco", "Arma", 1750, bonus_ataque=58, peso=0.6, raridade="Epico"),
    "estilete_perfurador_vazio": Equipamento("Estilete do Vazio", "Arma", 1900, bonus_ataque=64, peso=0.2, raridade="Epico"),
    "lamina_oculta_dual_b": Equipamento("Lâminas Ocultas Duplas (Rank B)", "Arma", 2200, bonus_ataque=70, peso=0.5, raridade="Epico"),
    "shuriken_estrela_cadente": Equipamento("Shuriken Estrela Cadente", "Arma", 1450, bonus_ataque=52, peso=0.1, raridade="Epico"),
    "adaga_obsidiana_alma": Equipamento("Obsidiana Devoradora de Almas", "Arma", 2350, bonus_ataque=74, peso=0.4, raridade="Epico"),
    "tanto_honra_perdida": Equipamento("Tantō da Honra Perdida", "Arma", 1800, bonus_ataque=60, peso=0.5, raridade="Epico"),
    "punhal_asa_morcego": Equipamento("Punhal Asa de Morcego", "Arma", 1650, bonus_ataque=56, peso=0.3, raridade="Epico"),
    "espada_curta_vagalume_negro": Equipamento("Vagalume Negro", "Arma", 2050, bonus_ataque=67, peso=1.0, raridade="Epico"),
    "faca_arremesso_relampago": Equipamento("Faca de Arremesso Relâmpago", "Arma", 1550, bonus_ataque=54, peso=0.2, raridade="Epico"),
    "adaga_dente_dragao_jovem": Equipamento("Dente de Dragão Jovem", "Arma", 2450, bonus_ataque=76, peso=0.6, raridade="Epico"),
    "kama_sangue_eterno": Equipamento("Kama de Sangue Eterno", "Arma", 1950, bonus_ataque=63, peso=0.7, raridade="Epico"),
    "lamina_sombra_viva": Equipamento("Lâmina da Sombra Viva", "Arma", 2150, bonus_ataque=69, peso=0.3, raridade="Epico"),
    "punhal_veneno_escorpião_rei": Equipamento("Punhal do Rei Escorpião", "Arma", 2000, bonus_ataque=66, peso=0.4, raridade="Epico"),
    "garra_falcão_ferro": Equipamento("Garras do Falcão de Ferro", "Arma", 1700, bonus_ataque=59, peso=0.5, raridade="Epico"),
    "adaga_estilhaço_estelar": Equipamento("Estilhaço Estelar", "Arma", 2250, bonus_ataque=72, peso=0.3, raridade="Epico"),
    "faca_ritual_sangrento": Equipamento("Faca de Ritual Sangrento", "Arma", 1500, bonus_ataque=53, peso=0.4, raridade="Epico"),
    "punhal_silencio_eterno": Equipamento("Silêncio Eterno", "Arma", 2500, bonus_ataque=78, peso=0.2, raridade="Epico"),
    "lamina_curva_eclipse": Equipamento("Lâmina do Eclipse", "Arma", 1850, bonus_ataque=61, peso=0.6, raridade="Epico"),
    "adaga_mergulhador_abissal": Equipamento("Mergulhador Abissal", "Arma", 2100, bonus_ataque=67, peso=0.5, raridade="Epico"),
    "kunai_tempestade_aço": Equipamento("Kunai da Tempestade", "Arma", 1600, bonus_ataque=55, peso=0.2, raridade="Epico"),
    "adaga_espinho_rosa_negra": Equipamento("Espinho da Rosa Negra", "Arma", 2300, bonus_ataque=73, peso=0.3, raridade="Epico"),
    "lamina_assassino_imperador": Equipamento("Lâmina do Assassino do Imperador", "Arma", 2600, bonus_ataque=80, peso=0.5, raridade="Epico"),

    # ARMADURAS (Defesa) (25 itens) - Defesa base: 40 a 70
    "traje_espectro_noturno": Equipamento("Traje do Espectro Noturno", "Armadura", 2800, bonus_defesa=58, peso=1.8, raridade="Epico"),
    "capuz_olhar_morte": Equipamento("Capuz Olhar da Morte", "Armadura", 1200, bonus_defesa=25, peso=0.3, raridade="Epico"),
    "botas_passo_fantasma": Equipamento("Botas do Passo Fantasma", "Armadura", 1100, bonus_defesa=22, peso=0.4, raridade="Epico"),
    "luvas_punho_sombrio": Equipamento("Luvas do Punho Sombrio", "Armadura", 1000, bonus_defesa=20, peso=0.2, raridade="Epico"),
    "mascara_sorriso_demoniaco": Equipamento("Máscara do Sorriso Demoníaco", "Armadura", 1400, bonus_defesa=30, peso=0.4, raridade="Epico"),
    "manto_nevoa_vazia": Equipamento("Manto da Névoa do Vazio", "Armadura", 3200, bonus_defesa=65, peso=1.0, raridade="Epico"),
    "peitoral_couro_draconico": Equipamento("Peitoral de Couro Dracônico", "Armadura", 3000, bonus_defesa=62, peso=3.0, raridade="Epico"),
    "braçadeiras_espinho_ferro": Equipamento("Braçadeiras de Espinho", "Armadura", 1150, bonus_defesa=24, peso=0.7, raridade="Epico"),
    "cinto_ferramentas_mestre": Equipamento("Cinto de Utilidades de Mestre", "Armadura", 950, bonus_defesa=18, peso=0.5, raridade="Epico"),
    "ombreiras_vaga_lume_negro": Equipamento("Ombreiras Vagalume Negro", "Armadura", 1050, bonus_defesa=21, peso=0.6, raridade="Epico"),
    "botas_agilidade_vortex": Equipamento("Botas de Agilidade Vórtex", "Armadura", 1300, bonus_defesa=28, peso=0.5, raridade="Epico"),
    "mascara_pesadelo_eterno": Equipamento("Máscara do Pesadelo Eterno", "Armadura", 1500, bonus_defesa=32, peso=0.3, raridade="Epico"),
    "perneiras_aço_astral_leve": Equipamento("Perneiras de Aço Astral Leve", "Armadura", 1250, bonus_defesa=27, peso=1.1, raridade="Epico"),
    "tunica_mestre_sombras": Equipamento("Túnica do Mestre das Sombras", "Armadura", 2900, bonus_defesa=60, peso=1.5, raridade="Epico"),
    "luvas_toque_paralizante": Equipamento("Luvas do Toque Paralisante", "Armadura", 1100, bonus_defesa=23, peso=0.2, raridade="Epico"),
    "ombreiras_asa_corvo": Equipamento("Ombreiras Asa de Corvo", "Armadura", 1000, bonus_defesa=20, peso=0.8, raridade="Epico"),
    "colete_couro_quimera": Equipamento("Colete de Couro de Quimera", "Armadura", 2700, bonus_defesa=56, peso=2.0, raridade="Epico"),
    "elmo_visão_noturna_real": Equipamento("Elmo da Visão Noturna Real", "Armadura", 1600, bonus_defesa=35, peso=0.7, raridade="Epico"),
    "braçadeiras_veneno_embutido": Equipamento("Braçadeiras de Veneno", "Armadura", 1350, bonus_defesa=29, peso=0.6, raridade="Epico"),
    "manto_escuridão_absoluta": Equipamento("Manto da Escuridão Absoluta", "Armadura", 3500, bonus_defesa=70, peso=1.2, raridade="Epico"),
    "botas_rastro_fogo_negro": Equipamento("Botas Rastro de Fogo Negro", "Armadura", 1450, bonus_defesa=31, peso=0.5, raridade="Epico"),
    "cinto_coldre_mestre": Equipamento("Cinto de Coldre de Mestre", "Armadura", 1100, bonus_defesa=23, peso=0.5, raridade="Epico"),
    "mascara_hannya_epica": Equipamento("Máscara Hannya (Rank B)", "Armadura", 1700, bonus_defesa=38, peso=0.4, raridade="Epico"),
    "peitoral_cristal_sombrio": Equipamento("Peitoral de Cristal Sombrio", "Armadura", 3100, bonus_defesa=64, peso=2.5, raridade="Epico"),
    "traje_camuflagem_espectral": Equipamento("Traje Camuflagem Espectral", "Armadura", 4000, bonus_defesa=75, peso=1.3, raridade="Epico"),
}

# --- ITENS ASSASSINO: LENDÁRIO (Rank A) (01-50) ---
ITENS_ASSASSINO_LENDARIO = {
    # ARMAS (Ataque) (25 itens) - Dano base: 110 a 160
    "adaga_monarca_sombras": Equipamento("Lâmina do Monarca das Sombras", "Arma", 9500, bonus_ataque=145, peso=0.3, raridade="Lendario"),
    "punhal_cinzas_fenix": Equipamento("Punhal das Cinzas da Fênix", "Arma", 8800, bonus_ataque=138, peso=0.2, raridade="Lendario"),
    "garra_fenris_lendaria": Equipamento("Garras de Fenris", "Arma", 9200, bonus_ataque=142, peso=0.6, raridade="Lendario"),
    "lamina_corte_espacial": Equipamento("Lâmina do Corte Espacial", "Arma", 10500, bonus_ataque=155, peso=0.4, raridade="Lendario"),
    "adaga_veneno_basilisco_real": Equipamento("Presa do Basilisco Real", "Arma", 8600, bonus_ataque=135, peso=0.3, raridade="Lendario"),
    "estilete_alma_vazia": Equipamento("Estilete da Alma Vazia", "Arma", 8200, bonus_ataque=130, peso=0.1, raridade="Lendario"),
    "tanto_mestre_kuran": Equipamento("Tantō do Mestre Kuran", "Arma", 9000, bonus_ataque=140, peso=0.5, raridade="Lendario"),
    "adaga_eclipse_eterno": Equipamento("Eclipse Eterno", "Arma", 9800, bonus_ataque=150, peso=0.3, raridade="Lendario"),
    "shuriken_supernova": Equipamento("Shuriken Supernova", "Arma", 7500, bonus_ataque=115, peso=0.1, raridade="Lendario"),
    "punhal_sopro_dragao_gelo": Equipamento("Sopro do Dragão de Gelo", "Arma", 8900, bonus_ataque=139, peso=0.4, raridade="Lendario"),
    "lamina_oculta_assassino_rei": Equipamento("Lâmina Oculta do Rei Assassino", "Arma", 11000, bonus_ataque=160, peso=0.5, raridade="Lendario"),
    "adaga_fragmento_lua_sangue": Equipamento("Fragmento da Lua de Sangue", "Arma", 8400, bonus_ataque=132, peso=0.3, raridade="Lendario"),
    "faca_arremesso_cometa": Equipamento("Faca de Arremesso Cometa", "Arma", 7800, bonus_ataque=125, peso=0.2, raridade="Lendario"),
    "punhal_mordida_lobo_branco": Equipamento("Mordida do Lobo Branco", "Arma", 8700, bonus_ataque=136, peso=0.4, raridade="Lendario"),
    "garra_behemoth_negro": Equipamento("Garras do Behemoth Negro", "Arma", 9400, bonus_ataque=144, peso=0.7, raridade="Lendario"),
    "adaga_tempestade_raios": Equipamento("Tormenta de Raios", "Arma", 9100, bonus_ataque=141, peso=0.3, raridade="Lendario"),
    "kama_ceifador_almas": Equipamento("Kama Ceifador de Almas", "Arma", 9300, bonus_ataque=143, peso=0.8, raridade="Lendario"),
    "lamina_caos_primordial": Equipamento("Lâmina do Caos Primordial", "Arma", 10200, bonus_ataque=152, peso=0.4, raridade="Lendario"),
    "punhal_beijo_serpente_mar": Equipamento("Beijo da Serpente do Mar", "Arma", 8500, bonus_ataque=134, peso=0.3, raridade="Lendario"),
    "adaga_estrela_poente": Equipamento("Estrela Poente", "Arma", 8000, bonus_ataque=128, peso=0.3, raridade="Lendario"),
    "estilete_cristal_vazio": Equipamento("Estilete de Cristal do Vazio", "Arma", 8300, bonus_ataque=131, peso=0.2, raridade="Lendario"),
    "tanto_crepusculo": Equipamento("Tantō do Crepúsculo", "Arma", 9600, bonus_ataque=148, peso=0.5, raridade="Lendario"),
    "adaga_presa_titan": Equipamento("Presa do Titã", "Arma", 8950, bonus_ataque=137, peso=0.4, raridade="Lendario"),
    "lamina_dual_nexus": Equipamento("Lâminas do Nexus", "Arma", 10800, bonus_ataque=158, peso=0.9, raridade="Lendario"),
    "punhal_vontade_deus_morto": Equipamento("Vontade do Deus Morto", "Arma", 11500, bonus_ataque=165, peso=0.3, raridade="Lendario"),

    # ARMADURAS (Defesa) (25 itens) - Defesa base: 85 a 135
    "manto_soberano_sombras": Equipamento("Manto do Soberano das Sombras", "Armadura", 12500, bonus_defesa=115, peso=1.0, raridade="Lendario"),
    "traje_caçador_rank_s": Equipamento("Traje do Caçador Rank S", "Armadura", 14000, bonus_defesa=130, peso=2.0, raridade="Lendario"),
    "capuz_visão_abissal": Equipamento("Capuz da Visão Abissal", "Armadura", 6000, bonus_defesa=55, peso=0.3, raridade="Lendario"),
    "botas_passo_celestial": Equipamento("Botas do Passo Celestial", "Armadura", 5800, bonus_defesa=52, peso=0.4, raridade="Lendario"),
    "luvas_toque_de_ouro": Equipamento("Luvas do Toque de Midas", "Armadura", 5500, bonus_defesa=50, peso=0.2, raridade="Lendario"),
    "mascara_vulto_eterno": Equipamento("Máscara do Vulto Eterno", "Armadura", 6500, bonus_defesa=58, peso=0.3, raridade="Lendario"),
    "peitoral_escamas_leviata": Equipamento("Peitoral de Escamas de Leviatã", "Armadura", 11000, bonus_defesa=105, peso=2.5, raridade="Lendario"),
    "braçadeiras_astral_lendarias": Equipamento("Braçadeiras Astrais", "Armadura", 5400, bonus_defesa=48, peso=0.6, raridade="Lendario"),
    "cinto_infinito_utilitario": Equipamento("Cinto do Infinito", "Armadura", 4800, bonus_defesa=42, peso=0.5, raridade="Lendario"),
    "manto_fenix_negra": Equipamento("Manto da Fênix Negra", "Armadura", 13500, bonus_defesa=125, peso=1.2, raridade="Lendario"),
    "botas_velocidade_luz": Equipamento("Botas da Velocidade da Luz", "Armadura", 6200, bonus_defesa=56, peso=0.4, raridade="Lendario"),
    "mascara_terror_ancião": Equipamento("Máscara do Terror Ancião", "Armadura", 6800, bonus_defesa=60, peso=0.4, raridade="Lendario"),
    "perneiras_aço_sagrado_leve": Equipamento("Perneiras de Aço Sagrado Leve", "Armadura", 5900, bonus_defesa=53, peso=1.0, raridade="Lendario"),
    "tunica_mestre_assassino_lendaria": Equipamento("Túnica do Mestre Absoluto", "Armadura", 12000, bonus_defesa=110, peso=1.4, raridade="Lendario"),
    "luvas_garra_dragao": Equipamento("Luvas Garra de Dragão", "Armadura", 5700, bonus_defesa=51, peso=0.3, raridade="Lendario"),
    "ombreiras_feras_lendarias": Equipamento("Ombreiras das Feras Lendárias", "Armadura", 5300, bonus_defesa=47, peso=0.8, raridade="Lendario"),
    "colete_couro_behemoth_rei": Equipamento("Colete do Rei Behemoth", "Armadura", 10500, bonus_defesa=100, peso=2.2, raridade="Lendario"),
    "elmo_olho_ciclope": Equipamento("Elmo do Olho de Ciclope", "Armadura", 6400, bonus_defesa=57, peso=0.7, raridade="Lendario"),
    "braçadeiras_sangue_eterno": Equipamento("Braçadeiras de Sangue Eterno", "Armadura", 5600, bonus_defesa=49, peso=0.5, raridade="Lendario"),
    "manto_nevoa_vazia_lendario": Equipamento("Manto da Névoa do Vazio", "Armadura", 13000, bonus_defesa=120, peso=1.1, raridade="Lendario"),
    "botas_onipresença_fraca": Equipamento("Botas do Passo Sombrio", "Armadura", 6300, bonus_defesa=57, peso=0.4, raridade="Lendario"),
    "cinto_soberania_assassino": Equipamento("Cinto da Soberania", "Armadura", 5200, bonus_defesa=46, peso=0.5, raridade="Lendario"),
    "mascara_oni_lendaria": Equipamento("Máscara Oni Suprema", "Armadura", 7000, bonus_defesa=62, peso=0.4, raridade="Lendario"),
    "peitoral_vanguarda_astral": Equipamento("Vanguarda Astral", "Armadura", 11800, bonus_defesa=108, peso=2.0, raridade="Lendario"),
    "traje_entidade_sombria": Equipamento("Traje da Entidade Sombria", "Armadura", 15000, bonus_defesa=140, peso=1.2, raridade="Lendario"),
}

# --- ITENS ASSASSINO: MÍTICO (Rank S) (01-50) ---
ITENS_ASSASSINO_MITICO = {
    # ARMAS (Ataque) (25 itens) - Dano base: 200 a 330
    "ira_de_kamish_assassino": Equipamento("Ira de Kamish (Versão Adaga)", "Arma", 45000, bonus_ataque=310, peso=0.3, raridade="Mitico"),
    "lamina_deus_morte": Equipamento("Lâmina do Deus da Morte", "Arma", 50000, bonus_ataque=330, peso=0.2, raridade="Mitico"),
    "punhal_vazio_absoluto": Equipamento("Punhal do Vazio Absoluto", "Arma", 42000, bonus_ataque=295, peso=0.1, raridade="Mitico"),
    "garra_fenrir_desperta": Equipamento("Garras de Fenrir Despertas", "Arma", 38000, bonus_ataque=280, peso=0.5, raridade="Mitico"),
    "estilete_divisor_dimensoes": Equipamento("Divisor de Dimensões", "Arma", 44000, bonus_ataque=305, peso=0.2, raridade="Mitico"),
    "adaga_sangue_monarca": Equipamento("Presa do Monarca Escarlate", "Arma", 41000, bonus_ataque=290, peso=0.3, raridade="Mitico"),
    "tanto_alma_ancestral": Equipamento("Tantō da Alma Ancestral", "Arma", 39000, bonus_ataque=285, peso=0.4, raridade="Mitico"),
    "lamina_eclipse_final": Equipamento("Eclipse Final (Dual)", "Arma", 48000, bonus_ataque=320, peso=0.6, raridade="Mitico"),
    "punhal_silencio_cosmico": Equipamento("Silêncio Cósmico", "Arma", 43000, bonus_ataque=300, peso=0.2, raridade="Mitico"),
    "adaga_presa_jormungand": Equipamento("Presa de Jormungand", "Arma", 46000, bonus_ataque=315, peso=0.4, raridade="Mitico"),
    "shuriken_buraco_negro": Equipamento("Shuriken Buraco Negro", "Arma", 35000, bonus_ataque=250, peso=0.1, raridade="Mitico"),
    "lamina_oculta_destino": Equipamento("Lâmina do Destino Oculto", "Arma", 47000, bonus_ataque=318, peso=0.5, raridade="Mitico"),
    "punhal_beijo_eternidade": Equipamento("Beijo da Eternidade", "Arma", 40000, bonus_ataque=288, peso=0.3, raridade="Mitico"),
    "adaga_coracao_estrela": Equipamento("Coração de Estrela Guia", "Arma", 42500, bonus_ataque=298, peso=0.3, raridade="Mitico"),
    "garra_sombra_primordial": Equipamento("Garras da Sombra Primordial", "Arma", 39500, bonus_ataque=282, peso=0.6, raridade="Mitico"),
    "faca_arremesso_infinito": Equipamento("Faca de Arremesso Infinita", "Arma", 36000, bonus_ataque=260, peso=0.2, raridade="Mitico"),
    "estilete_ponta_do_caos": Equipamento("Ponta do Caos", "Arma", 41500, bonus_ataque=292, peso=0.2, raridade="Mitico"),
    "adaga_suspiro_espectral": Equipamento("Suspiro Espectral", "Arma", 38500, bonus_ataque=278, peso=0.4, raridade="Mitico"),
    "lamina_dual_nexus_mitica": Equipamento("Lâminas do Nexus Eterno", "Arma", 49000, bonus_ataque=325, peso=0.8, raridade="Mitico"),
    "punhal_mordida_vazio": Equipamento("Mordida do Vazio", "Arma", 43500, bonus_ataque=302, peso=0.3, raridade="Mitico"),
    "kama_ceifeira_de_mundos": Equipamento("Kama Ceifeira de Mundos", "Arma", 45500, bonus_ataque=312, peso=0.7, raridade="Mitico"),
    "adaga_fragmento_genesis": Equipamento("Fragmento do Gênese", "Arma", 52000, bonus_ataque=340, peso=0.3, raridade="Mitico"),
    "tanto_luz_extinta": Equipamento("Tantō da Luz Extinta", "Arma", 40500, bonus_ataque=286, peso=0.4, raridade="Mitico"),
    "lamina_assassino_deuses": Equipamento("O Matador de Deuses", "Arma", 55000, bonus_ataque=350, peso=0.5, raridade="Mitico"),
    "adaga_essencia_noite": Equipamento("Essência da Noite Eterna", "Arma", 44500, bonus_ataque=308, peso=0.3, raridade="Mitico"),

    # ARMADURAS (Defesa) (25 itens) - Defesa base: 150 a 250
    "manto_onipresença_mitico": Equipamento("Manto da Onipresença", "Armadura", 60000, bonus_defesa=220, peso=0.5, raridade="Mitico"),
    "traje_avatar_sombra": Equipamento("Avatar da Sombra Final", "Armadura", 65000, bonus_defesa=240, peso=1.5, raridade="Mitico"),
    "capuz_olho_da_verdade": Equipamento("Olho da Verdade Divina", "Armadura", 30000, bonus_defesa=90, peso=0.2, raridade="Mitico"),
    "botas_passo_do_vazio": Equipamento("Botas do Passo do Vazio", "Armadura", 28000, bonus_defesa=85, peso=0.3, raridade="Mitico"),
    "luvas_toque_do_caos": Equipamento("Manoplas do Caos Primordial", "Armadura", 25000, bonus_defesa=75, peso=0.2, raridade="Mitico"),
    "mascara_vulto_mitico": Equipamento("Máscara do Vulto Ancestral", "Armadura", 32000, bonus_defesa=95, peso=0.2, raridade="Mitico"),
    "peitoral_couro_dragao_anciao": Equipamento("Escamas do Rei Dragão", "Armadura", 55000, bonus_defesa=210, peso=2.5, raridade="Mitico"),
    "braçadeiras_eter": Equipamento("Braçadeiras de Éter Estelar", "Armadura", 24000, bonus_defesa=70, peso=0.5, raridade="Mitico"),
    "cinto_origem_mundo": Equipamento("Cinto da Origem", "Armadura", 22000, bonus_defesa=65, peso=0.4, raridade="Mitico"),
    "manto_escuridao_viva": Equipamento("Manto da Escuridão Viva", "Armadura", 62000, bonus_defesa=230, peso=1.0, raridade="Mitico"),
    "botas_onipotencia_fraca": Equipamento("Botas da Onipotência", "Armadura", 31000, bonus_defesa=92, peso=0.4, raridade="Mitico"),
    "mascara_devoradora_almas": Equipamento("Máscara Devoradora de Almas", "Armadura", 33000, bonus_defesa=98, peso=0.3, raridade="Mitico"),
    "perneiras_aço_vazio": Equipamento("Perneiras de Aço do Vazio", "Armadura", 27000, bonus_defesa=82, peso=0.9, raridade="Mitico"),
    "tunica_entidade_mitica": Equipamento("Túnica da Entidade Suprema", "Armadura", 70000, bonus_defesa=260, peso=1.2, raridade="Mitico"),
    "luvas_precisao_deus": Equipamento("Punhos da Precisão Divina", "Armadura", 26000, bonus_defesa=78, peso=0.2, raridade="Mitico"),
    "ombreiras_asas_anjo_caido": Equipamento("Ombreiras do Anjo Caído", "Armadura", 23000, bonus_defesa=68, peso=0.7, raridade="Mitico"),
    "colete_couro_fenrir": Equipamento("Colete de Couro de Fenrir", "Armadura", 52000, bonus_defesa=195, peso=2.0, raridade="Mitico"),
    "elmo_coroa_das_sombras": Equipamento("Coroa das Sombras", "Armadura", 34000, bonus_defesa=105, peso=0.5, raridade="Mitico"),
    "braçadeiras_vontade_ferrea": Equipamento("Braçadeiras da Vontade Divina", "Armadura", 25500, bonus_defesa=76, peso=0.4, raridade="Mitico"),
    "manto_constelação_negra": Equipamento("Manto da Constelação Negra", "Armadura", 64000, bonus_defesa=235, peso=1.1, raridade="Mitico"),
    "botas_velocidade_absoluta": Equipamento("Botas da Velocidade Absoluta", "Armadura", 32000, bonus_defesa=94, peso=0.4, raridade="Mitico"),
    "cinto_soberano_vazio": Equipamento("Cinto do Soberano do Vazio", "Armadura", 24500, bonus_defesa=72, peso=0.5, raridade="Mitico"),
    "mascara_pesadelo_mitico": Equipamento("Mascara do Pesadelo Real", "Armadura", 35000, bonus_defesa=110, peso=0.3, raridade="Mitico"),
    "peitoral_vanguarda_eterna": Equipamento("Vanguarda do Infinito", "Armadura", 58000, bonus_defesa=215, peso=1.8, raridade="Mitico"),
    "armadura_espectral_rei": Equipamento("Armadura Espectral do Rei", "Armadura", 80000, bonus_defesa=300, peso=1.0, raridade="Mitico"),
}